ARG DOTNET_VERSION


FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as builder

COPY libs /build/libs
COPY src /build/src
COPY docker/export/tests_appsettings.json /build/src/Services/Export/WB.Services.Export.Tests/appsettings.json
COPY docker/export/tests_appsettings.json /build/src/Services/Core/WB.Services.Scheduler.Tests/appsettings.json 
RUN dotnet build /build/src/Services/WB.Services.sln -c Release\
  && dotnet test /build/src/Services/Export//WB.Services.Export.Tests/WB.Services.Export.Tests.csproj\
  && dotnet test /build/src/Services/Core/WB.Services.Scheduler.Tests/WB.Services.Scheduler.Tests.csproj\
  && dotnet publish /build/src/Services/Export/WB.Services.Export.Host/WB.Services.Export.Host.csproj -c Release --no-restore -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:${DOTNET_VERSION}
COPY --from=builder app /app
COPY docker/export/appsettings.Production.ini /app/

WORKDIR /app

EXPOSE 80

ENTRYPOINT ["dotnet", "WB.Services.Export.Host.dll", "--kestrel"]
