<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidApplication>true</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>
    <ApplicationId>wb.tests.android.instrumentation</ApplicationId>
    <ApplicationManifest>Properties\AndroidManifest.xml</ApplicationManifest>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Android.NUnitRunner" Version="2.0.11" />
    <PackageReference Include="NUnit" Version="4.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\UI\Shared\WB.UI.Shared.Enumerator\WB.UI.Shared.Enumerator.csproj" />
  </ItemGroup>
</Project>
