<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Debug-ESRI;Release</Configurations>
    <RootNamespace>WB.Tests.Android.Instrumentation</RootNamespace>
    <AssemblyName>WB.Tests.Android.Instrumentation</AssemblyName>
    <ApplicationId>wb.tests.android.instrumentation</ApplicationId>
    <ApplicationTitle>WB.Tests.Android.Instrumentation</ApplicationTitle>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <ApplicationManifest>Properties\AndroidManifest.xml</ApplicationManifest>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\..\</SolutionDir>
    <WarningLevel>3</WarningLevel>
    <NoWarn>1701;1702;1705;612;618;1030;CA1416;CA1422</NoWarn>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' or '$(Configuration)' == 'Debug-ESRI'">
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Properties\AndroidManifest.xml">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UI\Shared\WB.UI.Shared.Enumerator\WB.UI.Shared.Enumerator.csproj" />
    <ProjectReference Include="..\..\Core\SharedKernels\Enumerator\Enumerator\WB.Core.SharedKernels.Enumerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnitLite" Version="4.3.2" />
  </ItemGroup>
</Project>



