//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.Core.SharedKernels.SurveyManagement.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterviewerSyncStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterviewerSyncStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.Core.SharedKernels.SurveyManagement.Web.Resources.InterviewerSyncStrings", typeof(InterviewerSyncStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Android device id was not provided. Please contact developers..
        /// </summary>
        internal static string AndroidDeviceIdWasNotProvided {
            get {
                return ResourceManager.GetString("AndroidDeviceIdWasNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. File with latest version was not found. Please contact developers..
        /// </summary>
        internal static string FileWasNotFound {
            get {
                return ResourceManager.GetString("FileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Incorrect files count. Please contact developers..
        /// </summary>
        internal static string IncorrectFilesCount {
            get {
                return ResourceManager.GetString("IncorrectFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Incorrect media type. Please contact developers..
        /// </summary>
        internal static string IncorrectMediaType {
            get {
                return ResourceManager.GetString("IncorrectMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Interviewer application has higher version &apos;{0}&apos; than Supervisor &apos;{1}&apos;..
        /// </summary>
        internal static string InterviewerApplicationHasHigherVersion_thanSupervisor_Format {
            get {
                return ResourceManager.GetString("InterviewerApplicationHasHigherVersion_thanSupervisor_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Please uninstall Interviewer application and install it..
        /// </summary>
        internal static string InterviewerApplicationHasVersion_butSupervisorHas_PleaseReinstallInterviewerApplication {
            get {
                return ResourceManager.GetString("InterviewerApplicationHasVersion_butSupervisorHas_PleaseReinstallInterviewerAppli" +
                        "cation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Interviewer application has version &apos;{0}&apos; but Supervisor has &apos;{1}&apos;. Please update Interviewer application..
        /// </summary>
        internal static string InterviewerApplicationHasVersion_butSupervisorHas_PleaseUpdateInterviewerApplication {
            get {
                return ResourceManager.GetString("InterviewerApplicationHasVersion_butSupervisorHas_PleaseUpdateInterviewerApplicat" +
                        "ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Your application is not compatible with server one. Uninstall your application and download new version of Interviewer app.
        /// </summary>
        internal static string InterviewerIsNotCompatibleWithThisVersion {
            get {
                return ResourceManager.GetString("InterviewerIsNotCompatibleWithThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device identifier. Something has happened with the client app installation, please send tablet information..
        /// </summary>
        internal static string InvalidDeviceIdentifier {
            get {
                return ResourceManager.GetString("InvalidDeviceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Invalid sequence identifier. Something has happened with the client app installation, press &quot;Send tablet information&quot; button..
        /// </summary>
        internal static string InvalidSequenceIdentifier {
            get {
                return ResourceManager.GetString("InvalidSequenceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. User is not authorized. Please check your login/password for {0}..
        /// </summary>
        internal static string InvalidUserFormat {
            get {
                return ResourceManager.GetString("InvalidUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Your account does not have an interviewer role. Please contact your supervisor..
        /// </summary>
        internal static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is on the maintenance mode now. Sorry for the inconvenience. Please, try again later..
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Please reinstall application. Installation identifier is missing. Please contact developers..
        /// </summary>
        internal static string NoClientIdentifier {
            get {
                return ResourceManager.GetString("NoClientIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Internal server error occurred. Please contact developers..
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.  Sync package with id &apos;{0}&apos; was not found on server. Please contact developers..
        /// </summary>
        internal static string Sync_package_with_id__0__was_not_found_on_serverFormat {
            get {
                return ResourceManager.GetString("Sync_package_with_id__0__was_not_found_on_serverFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Wrong android device id was provided. Please contact developers..
        /// </summary>
        internal static string WrongAndroidDeviceIdWasProvided {
            get {
                return ResourceManager.GetString("WrongAndroidDeviceIdWasProvided", resourceCulture);
            }
        }
    }
}
