version: '3'

services:
  headquarters:
    build: 
      context: .
      dockerfile: ./Dockerfile.hq
  export:
    build: 
      context: .
      dockerfile: ./Dockerfile.export
  webtester:
    build:
      context: .
      dockerfile: ./Dockerfile.webtester
  designer:
    build:
      context: .
      dockerfile: ./Dockerfile.designer
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: designer
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    