# for localhost http://localhost/headquarters
# baseUri: https://superhq-dev.mysurvey.solutions 
baseUri: http://localhost/headquarters
# should not be protected by spam filter (captcha)
questionarieId: a43e9bcdc4da41c2bec49f8d684ac252$16

# max random delay for answering per each bot in ms
answerDelay: 500

workersCount: 3

# max random delay for creating interview in ms
createInterviewDelay: 1000

# answers - arguments order can be seen from application or devs
answers:
- ['answerTextQuestion', '81a45b78bdc80562e092cbeb70175dee','test1' ]
- ['answerTextQuestion', '81a45b78bdc80562e092cbeb70175dee','test3' ]
- ['answerTextQuestion', '81a45b78bdc80562e092cbeb70175dee','test6' ]
- ['answerTextQuestion', '81a45b78bdc80562e092cbeb70175dee','test4' ]
- ['answerIntegerQuestion', '8fe65f61b8f074a786cac4cbc32d949d', '325' ]
- ['answerIntegerQuestion', '8fe65f61b8f074a786cac4cbc32d949d', '444' ]
- ['answerIntegerQuestion', '8fe65f61b8f074a786cac4cbc32d949d', '456234' ]
- ['answerIntegerQuestion', '8fe65f61b8f074a786cac4cbc32d949d', '23423'  ]
- ['answerSingleOptionQuestion', '2', '108827b67d06861f0ba1c135192d3f35' ]