// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WB.Core.BoundedContexts.Designer.Implementation.Services.CodeGeneration.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Main.Core.Entities.SubEntities;
    using System.Text.RegularExpressions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class InterviewExpressionStateTemplate : InterviewExpressionStateTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Text.RegularExpressions;\r\n\r\nnamespace WB.Core.SharedKernels.DataCollection.Gen" +
                    "erated\r\n{\r\n    public class ");
            
            #line 15 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.GeneratedClassName));
            
            #line default
            #line hidden
            this.Write(" : AbstractInterviewExpressionState \r\n    {\r\n        public ");
            
            #line 17 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.GeneratedClassName));
            
            #line default
            #line hidden
            this.Write("() \r\n        {\r\n            var questionnaireLevelScope = new[] { IdOf.@__questio" +
                    "nnaire };\r\n            var questionnaireIdentityKey = Util.GetRosterKey(question" +
                    "naireLevelScope, Util.EmptyRosterVector);\r\n            var questionnaireLevel = " +
                    "new ");
            
            #line 21 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.QuestionnaireLevelModel.GeneratedTypeName));
            
            #line default
            #line hidden
            this.Write(@"(Util.EmptyRosterVector, questionnaireIdentityKey, this.GetRosterInstances, IdOf.conditionalDependencies, IdOf.structuralDependencies);
            this.InterviewScopes.Add(Util.GetRosterStringKey(questionnaireIdentityKey), questionnaireLevel);
        }

        private ");
            
            #line 25 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.GeneratedClassName));
            
            #line default
            #line hidden
            this.Write("(Dictionary<string, IExpressionExecutable> interviewScopes, Dictionary<string, Li" +
                    "st<string>> siblingRosters)\r\n        {\r\n            var newScopes = interviewSco" +
                    "pes.ToDictionary(interviewScope => interviewScope.Key, interviewScope => intervi" +
                    "ewScope.Value.CopyMembers(this.GetRosterInstances));\r\n\r\n            var newSibli" +
                    "ngRosters = siblingRosters\r\n                .ToDictionary(\r\n                    " +
                    "interviewScope => interviewScope.Key,\r\n                    interviewScope => new" +
                    " List<string>(interviewScope.Value));\r\n\r\n            //set parents\r\n            " +
                    "foreach (var interviewScope in interviewScopes)\r\n            {\r\n                " +
                    "var parent = interviewScope.Value.GetParent();\r\n                if (parent != nu" +
                    "ll)\r\n                    newScopes[interviewScope.Key].SetParent(newScopes[Util." +
                    "GetRosterStringKey(parent.GetRosterKey())]);\r\n            }\r\n\r\n            this." +
                    "InterviewScopes = newScopes;\r\n            this.SiblingRosters = newSiblingRoster" +
                    "s;\r\n        }\r\n\r\n\t\tpublic override bool HasParentMapSuchRoster(Guid rosterId)\r\n " +
                    "       {\r\n            return IdOf.parentScopeMap.ContainsKey(rosterId);\r\n       " +
                    " }\r\n\r\n\t\tpublic override Guid GetQuestionnaireId()\r\n        {\r\n            return" +
                    " IdOf.@__questionnaire;\r\n        }\r\n\r\n\t\tpublic override Guid[] GetRosterParentSc" +
                    "opeMap(Guid rosterId)\r\n\t\t{\r\n\t\t\treturn IdOf.parentScopeMap[rosterId];\r\n\t\t}\r\n\r\n   " +
                    "     public override Dictionary<Guid, Guid[]> GetParentsMap()\r\n        {\r\n      " +
                    "      return IdOf.parentScopeMap;\r\n        }\r\n\r\n        public override IIntervi" +
                    "ewExpressionState Clone()\r\n        {\r\n            return new ");
            
            #line 68 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.GeneratedClassName));
            
            #line default
            #line hidden
            this.Write("(this.InterviewScopes, this.SiblingRosters);\r\n        }\r\n    }\r\n\r\n\r\n        //gen" +
                    "erate QuestionnaireLevel\r\n        ");
            
            #line 74 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
           
            QuestionnaireLevelTemplate questionnairetemplate = new QuestionnaireLevelTemplate(QuestionnaireTemplateStructure.QuestionnaireLevelModel);
            this.Write(questionnairetemplate.TransformText());                           
         
            
            #line default
            #line hidden
            this.Write("\r\n        //generating rosters\r\n        ");
            
            #line 80 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var rosterGroup in QuestionnaireTemplateStructure.RostersGroupedByScope) 
           {
                RosterScopeTemplate template = new RosterScopeTemplate(rosterGroup, QuestionnaireTemplateStructure, QuestionnaireTemplateStructure.GenerateEmbeddedExpressionMethods);
                this.Write(template.TransformText());
                
           }
        
            
            #line default
            #line hidden
            this.Write("\r\n        public static class IdOf\r\n        {\r\n            public static readonly" +
                    " Guid @__questionnaire = Guid.Parse(\"");
            
            #line 90 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.Id));
            
            #line default
            #line hidden
            this.Write("\"); \r\n            //questions\r\n            ");
            
            #line 92 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var q in QuestionnaireTemplateStructure.AllQuestions) 
            {
            
            #line default
            #line hidden
            this.Write("            public static readonly Guid ");
            
            #line 94 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(q.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(" = Guid.Parse(\"");
            
            #line 94 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(q.Id));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 95 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            //groups\r\n            ");
            
            #line 97 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var g in QuestionnaireTemplateStructure.AllGroups) 
            {
            
            #line default
            #line hidden
            this.Write("            public static readonly Guid ");
            
            #line 99 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(" = Guid.Parse(\"");
            
            #line 99 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Id));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 100 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            //rosters\r\n            ");
            
            #line 102 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var r in QuestionnaireTemplateStructure.AllRosters) 
            {
            
            #line default
            #line hidden
            this.Write("            public static readonly Guid ");
            
            #line 104 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(" = Guid.Parse(\"");
            
            #line 104 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.Id));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 105 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            \r\n            public static readonly Guid[] ");
            
            #line 107 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QuestionnaireTemplateStructure.QuestionnaireLevelModel.GeneratedRosterScopeName));
            
            #line default
            #line hidden
            this.Write(" = new[] {@__questionnaire};\r\n\r\n            ");
            
            #line 109 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var r in QuestionnaireTemplateStructure.AllRosters)
            {
            
            #line default
            #line hidden
            this.Write("            public static readonly Guid[] ");
            
            #line 111 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.GeneratedRosterScopeName));
            
            #line default
            #line hidden
            this.Write(" = new[] {");
            
            #line 111 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(" ,", r.RosterScope.Select(g => string.Format("Guid.Parse(\"{0}\")", g)).ToArray())));
            
            #line default
            #line hidden
            this.Write("};\r\n            ");
            
            #line 112 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            \r\n            public static Dictionary<Guid, Guid[]> conditionalDepen" +
                    "dencies = new Dictionary<Guid, Guid[]>()\r\n            {            \r\n           " +
                    "     ");
            
            #line 116 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var dependency in QuestionnaireTemplateStructure.ConditionalDependencies)
                {
            
            #line default
            #line hidden
            this.Write("                {Guid.Parse(\"");
            
            #line 118 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Key));
            
            #line default
            #line hidden
            this.Write("\"), new Guid[]{\r\n                ");
            
            #line 119 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var dependencyValue in dependency.Value)
                {
            
            #line default
            #line hidden
            this.Write("                    Guid.Parse(\"");
            
            #line 121 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependencyValue));
            
            #line default
            #line hidden
            this.Write("\"),\r\n                ");
            
            #line 122 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                }},\r\n                ");
            
            #line 124 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            };\r\n\r\n            public static Dictionary<Guid, Guid[]> structuralDe" +
                    "pendencies = new Dictionary<Guid, Guid[]>()\r\n            {\r\n                ");
            
            #line 129 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var dependency in QuestionnaireTemplateStructure.StructuralDependencies) 
                {
            
            #line default
            #line hidden
            this.Write("                { Guid.Parse(\"");
            
            #line 131 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Key));
            
            #line default
            #line hidden
            this.Write("\"), new Guid[]{\r\n                ");
            
            #line 132 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var d in dependency.Value)
                {
            
            #line default
            #line hidden
            this.Write("                    Guid.Parse(\"");
            
            #line 134 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(d));
            
            #line default
            #line hidden
            this.Write("\"),\r\n                ");
            
            #line 135 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                }},\r\n                ");
            
            #line 137 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("            };\r\n\r\n            public static Dictionary<Guid, Guid[]> parentScopeM" +
                    "ap = new Dictionary<Guid, Guid[]>\r\n            {\r\n                //questions\r\n " +
                    "               ");
            
            #line 143 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var q in QuestionnaireTemplateStructure.AllQuestions) 
                {
            
            #line default
            #line hidden
            this.Write("                {");
            
            #line 145 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(q.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 145 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(q.RosterScopeName));
            
            #line default
            #line hidden
            this.Write("},\r\n                ");
            
            #line 146 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                //groups\r\n                ");
            
            #line 148 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var g in QuestionnaireTemplateStructure.AllGroups) 
                {
            
            #line default
            #line hidden
            this.Write("                {");
            
            #line 150 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 150 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.RosterScopeName));
            
            #line default
            #line hidden
            this.Write("},\r\n                ");
            
            #line 151 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                //rosters\r\n                ");
            
            #line 153 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
foreach (var r in QuestionnaireTemplateStructure.AllRosters)
                {
            
            #line default
            #line hidden
            this.Write("                {");
            
            #line 155 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.GeneratedIdName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 155 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.GeneratedRosterScopeName));
            
            #line default
            #line hidden
            this.Write("},\r\n                ");
            
            #line 156 "C:\Work\WBCAPI\src\Core\BoundedContexts\Designer\WB.Core.BoundedContexts.Designer\Implementation\Services\CodeGeneration\Templates\InterviewExpressionStateTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("                                        \r\n            };\r\n        }\r\n    \r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class InterviewExpressionStateTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
