//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuestionnaireImport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionnaireImport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.QuestionnaireImport", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before log in, please make sure that the &apos;Designer&apos; website is available and it&apos;s not in the maintenance mode.
        /// </summary>
        internal static string BeforeSignInToDesigner {
            get {
                return ResourceManager.GetString("BeforeSignInToDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can automaticly add this questionnaire to all your devises.
        /// </summary>
        internal static string CensusImportSubTitle {
            get {
                return ResourceManager.GetString("CensusImportSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import this questionaire in census mode.
        /// </summary>
        internal static string CensusImportTitle {
            get {
                return ResourceManager.GetString("CensusImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer Questionnaires.
        /// </summary>
        internal static string DesignerQuestionnaires {
            get {
                return ResourceManager.GetString("DesignerQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-sections.
        /// </summary>
        internal static string Gropus {
            get {
                return ResourceManager.GetString("Gropus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import as template.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import it as new version, №{0}.
        /// </summary>
        internal static string ImportAsNewVersion {
            get {
                return ResourceManager.GetString("ImportAsNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import with census mode.
        /// </summary>
        internal static string ImportInCensus {
            get {
                return ResourceManager.GetString("ImportInCensus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Questionnaire:.
        /// </summary>
        internal static string ImportModePageTitle {
            get {
                return ResourceManager.GetString("ImportModePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire import mode.
        /// </summary>
        internal static string ImportModeTitle {
            get {
                return ResourceManager.GetString("ImportModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified at.
        /// </summary>
        internal static string LastModifiedAt {
            get {
                return ResourceManager.GetString("LastModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of my questionnaires.
        /// </summary>
        internal static string ListOfMyQuestionnaires {
            get {
                return ResourceManager.GetString("ListOfMyQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to designer. Please check that designer is available and try &lt;a href=&apos;{0}&apos;&gt;again&lt;/a&gt;.
        /// </summary>
        internal static string LoginToDesignerError {
            get {
                return ResourceManager.GetString("LoginToDesignerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is already exist on your list.
        /// </summary>
        internal static string QuestionnaireExists {
            get {
                return ResourceManager.GetString("QuestionnaireExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of them with conditions.
        /// </summary>
        internal static string QuestionsWithConditions {
            get {
                return ResourceManager.GetString("QuestionsWithConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import this questionaire as a template for individual assignments.
        /// </summary>
        internal static string RegularImportTitle {
            get {
                return ResourceManager.GetString("RegularImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosters.
        /// </summary>
        internal static string Rosters {
            get {
                return ResourceManager.GetString("Rosters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to designer.
        /// </summary>
        internal static string SignInToDesigner {
            get {
                return ResourceManager.GetString("SignInToDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to designer.
        /// </summary>
        internal static string SignInToDesignerTitle {
            get {
                return ResourceManager.GetString("SignInToDesignerTitle", resourceCulture);
            }
        }
    }
}
