//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.UI.Headquarters.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WB.UI.Headquarters.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ExportEncryption_Title {
            get {
                return ResourceManager.GetString("ExportEncryption_Title", resourceCulture);
            }
        }
        
        public static string ClearExportCache_Title {
            get {
                return ResourceManager.GetString("ClearExportCache_Title", resourceCulture);
            }
        }
        
        public static string ClearExportCache_Description {
            get {
                return ResourceManager.GetString("ClearExportCache_Description", resourceCulture);
            }
        }
        
        public static string RemoveExportCache {
            get {
                return ResourceManager.GetString("RemoveExportCache", resourceCulture);
            }
        }
        
        public static string RemoveExportCacheConfirm {
            get {
                return ResourceManager.GetString("RemoveExportCacheConfirm", resourceCulture);
            }
        }
        
        public static string RemoveExportCacheSuccess {
            get {
                return ResourceManager.GetString("RemoveExportCacheSuccess", resourceCulture);
            }
        }
        
        public static string RemovingExportCache {
            get {
                return ResourceManager.GetString("RemovingExportCache", resourceCulture);
            }
        }
        
        public static string RemoveExportCacheFail {
            get {
                return ResourceManager.GetString("RemoveExportCacheFail", resourceCulture);
            }
        }
        
        public static string RemoveExportCacheGeneratingFail {
            get {
                return ResourceManager.GetString("RemoveExportCacheGeneratingFail", resourceCulture);
            }
        }
        
        public static string RemoveExportCache_Warning {
            get {
                return ResourceManager.GetString("RemoveExportCache_Warning", resourceCulture);
            }
        }
        
        public static string RegeneratePasswordConfirm {
            get {
                return ResourceManager.GetString("RegeneratePasswordConfirm", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string ExportEncryptionSettings {
            get {
                return ResourceManager.GetString("ExportEncryptionSettings", resourceCulture);
            }
        }
        
        public static string EnableEncryption {
            get {
                return ResourceManager.GetString("EnableEncryption", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string GlobalNotice {
            get {
                return ResourceManager.GetString("GlobalNotice", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string LogoUpdated {
            get {
                return ResourceManager.GetString("LogoUpdated", resourceCulture);
            }
        }
        
        public static string UserProfileSettings_Title {
            get {
                return ResourceManager.GetString("UserProfileSettings_Title", resourceCulture);
            }
        }
        
        public static string WebInterviewEmailNotifications_Title {
            get {
                return ResourceManager.GetString("WebInterviewEmailNotifications_Title", resourceCulture);
            }
        }
        
        public static string MobileAppSettings_Title {
            get {
                return ResourceManager.GetString("MobileAppSettings_Title", resourceCulture);
            }
        }
        
        public static string MobileAppSettings_Description {
            get {
                return ResourceManager.GetString("MobileAppSettings_Description", resourceCulture);
            }
        }
        
        public static string AllowInterviewerUpdateProfile {
            get {
                return ResourceManager.GetString("AllowInterviewerUpdateProfile", resourceCulture);
            }
        }
        
        public static string AllowWebInterviewEmailNotifications {
            get {
                return ResourceManager.GetString("AllowWebInterviewEmailNotifications", resourceCulture);
            }
        }
        
        public static string AllowInterviewerUpdateProfileDesc {
            get {
                return ResourceManager.GetString("AllowInterviewerUpdateProfileDesc", resourceCulture);
            }
        }
        
        public static string AllowWebInterviewEmailNotificationsDesc {
            get {
                return ResourceManager.GetString("AllowWebInterviewEmailNotificationsDesc", resourceCulture);
            }
        }
        
        public static string InterviewerAutoUpdate {
            get {
                return ResourceManager.GetString("InterviewerAutoUpdate", resourceCulture);
            }
        }
        
        public static string InterviewerAutoUpdateEnabled {
            get {
                return ResourceManager.GetString("InterviewerAutoUpdateEnabled", resourceCulture);
            }
        }
        
        public static string InterviewerAutoUpdateDisabled {
            get {
                return ResourceManager.GetString("InterviewerAutoUpdateDisabled", resourceCulture);
            }
        }
        
        public static string LogoNotUpdated {
            get {
                return ResourceManager.GetString("LogoNotUpdated", resourceCulture);
            }
        }
        
        public static string ChangeStateConfirm {
            get {
                return ResourceManager.GetString("ChangeStateConfirm", resourceCulture);
            }
        }
        
        public static string ChangeStateDisabledConfirm {
            get {
                return ResourceManager.GetString("ChangeStateDisabledConfirm", resourceCulture);
            }
        }
        
        public static string GlobalNoteSettings {
            get {
                return ResourceManager.GetString("GlobalNoteSettings", resourceCulture);
            }
        }
        
        public static string LogoSettings {
            get {
                return ResourceManager.GetString("LogoSettings", resourceCulture);
            }
        }
        
        public static string RemoveLogo {
            get {
                return ResourceManager.GetString("RemoveLogo", resourceCulture);
            }
        }
        
        public static string GlobalNoteSaved {
            get {
                return ResourceManager.GetString("GlobalNoteSaved", resourceCulture);
            }
        }
        
        public static string ExportEncryption_Description {
            get {
                return ResourceManager.GetString("ExportEncryption_Description", resourceCulture);
            }
        }
        
        public static string GlobalNoteSettings_Description {
            get {
                return ResourceManager.GetString("GlobalNoteSettings_Description", resourceCulture);
            }
        }
        
        public static string LogoSettings_Description {
            get {
                return ResourceManager.GetString("LogoSettings_Description", resourceCulture);
            }
        }
        
        public static string LogoSettings_Description1 {
            get {
                return ResourceManager.GetString("LogoSettings_Description1", resourceCulture);
            }
        }
        
        public static string CurrentLogo {
            get {
                return ResourceManager.GetString("CurrentLogo", resourceCulture);
            }
        }
        
        public static string GlobalNoteClearingConfirm {
            get {
                return ResourceManager.GetString("GlobalNoteClearingConfirm", resourceCulture);
            }
        }
        
        public static string AutoUpdateDescription {
            get {
                return ResourceManager.GetString("AutoUpdateDescription", resourceCulture);
            }
        }
        
        public static string InterviewerPartialSynchronization {
            get {
                return ResourceManager.GetString("InterviewerPartialSynchronization", resourceCulture);
            }
        }
        
        public static string PartialSynchronizationDescription {
            get {
                return ResourceManager.GetString("PartialSynchronizationDescription", resourceCulture);
            }
        }
        
        public static string InterviewerGeographyQuestionAccuracyInMeters {
            get {
                return ResourceManager.GetString("InterviewerGeographyQuestionAccuracyInMeters", resourceCulture);
            }
        }
        
        public static string GeographyQuestionAccuracyInMetersDescription {
            get {
                return ResourceManager.GetString("GeographyQuestionAccuracyInMetersDescription", resourceCulture);
            }
        }
        
        public static string InterviewerGeographyQuestionPeriodInSeconds {
            get {
                return ResourceManager.GetString("InterviewerGeographyQuestionPeriodInSeconds", resourceCulture);
            }
        }
        
        public static string GeographyQuestionPeriodInSecondsDescription {
            get {
                return ResourceManager.GetString("GeographyQuestionPeriodInSecondsDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_Amazon {
            get {
                return ResourceManager.GetString("EmailProvider_Amazon", resourceCulture);
            }
        }
        
        public static string EmailProvider_None {
            get {
                return ResourceManager.GetString("EmailProvider_None", resourceCulture);
            }
        }
        
        public static string EmailProvider_Sendgrid {
            get {
                return ResourceManager.GetString("EmailProvider_Sendgrid", resourceCulture);
            }
        }
        
        public static string EmailProvider_NoneDescription {
            get {
                return ResourceManager.GetString("EmailProvider_NoneDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_AmazonDescription {
            get {
                return ResourceManager.GetString("EmailProvider_AmazonDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendgridDescription {
            get {
                return ResourceManager.GetString("EmailProvider_SendgridDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_SenderAddress {
            get {
                return ResourceManager.GetString("EmailProvider_SenderAddress", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendGridApiKey {
            get {
                return ResourceManager.GetString("EmailProvider_SendGridApiKey", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsAccessKeyId {
            get {
                return ResourceManager.GetString("EmailProvider_AwsAccessKeyId", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsSecretAccessKey {
            get {
                return ResourceManager.GetString("EmailProvider_AwsSecretAccessKey", resourceCulture);
            }
        }
        
        public static string EmailProvider_TestEmailAddress {
            get {
                return ResourceManager.GetString("EmailProvider_TestEmailAddress", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendTestEmail {
            get {
                return ResourceManager.GetString("EmailProvider_SendTestEmail", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendTestEmailResult {
            get {
                return ResourceManager.GetString("EmailProvider_SendTestEmailResult", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendTestEmailHeader {
            get {
                return ResourceManager.GetString("EmailProvider_SendTestEmailHeader", resourceCulture);
            }
        }
        
        public static string EmailProvider_PageDesc {
            get {
                return ResourceManager.GetString("EmailProvider_PageDesc", resourceCulture);
            }
        }
        
        public static string EmailProvider_SenderHeader {
            get {
                return ResourceManager.GetString("EmailProvider_SenderHeader", resourceCulture);
            }
        }
        
        public static string EmailProvider_SenderHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SenderHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_ReplyAddressHelp {
            get {
                return ResourceManager.GetString("EmailProvider_ReplyAddressHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SenderName {
            get {
                return ResourceManager.GetString("EmailProvider_SenderName", resourceCulture);
            }
        }
        
        public static string EmailProvider_ReplyAddress {
            get {
                return ResourceManager.GetString("EmailProvider_ReplyAddress", resourceCulture);
            }
        }
        
        public static string EmailProvider_SenderNameHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SenderNameHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_Address {
            get {
                return ResourceManager.GetString("EmailProvider_Address", resourceCulture);
            }
        }
        
        public static string EmailProvider_AddressHelp {
            get {
                return ResourceManager.GetString("EmailProvider_AddressHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_ServiceProvideHeader {
            get {
                return ResourceManager.GetString("EmailProvider_ServiceProvideHeader", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsAccessKeyIdHelp {
            get {
                return ResourceManager.GetString("EmailProvider_AwsAccessKeyIdHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsSecretAccessKeyHelp {
            get {
                return ResourceManager.GetString("EmailProvider_AwsSecretAccessKeyHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsRegion {
            get {
                return ResourceManager.GetString("EmailProvider_AwsRegion", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsRegionHelp {
            get {
                return ResourceManager.GetString("EmailProvider_AwsRegionHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_AwsRegion_Unknown {
            get {
                return ResourceManager.GetString("EmailProvider_AwsRegion_Unknown", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendGridApiKeyHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SendGridApiKeyHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_GeneralError {
            get {
                return ResourceManager.GetString("EmailProvider_GeneralError", resourceCulture);
            }
        }
        
        public static string EmailProvider_HelpLinkText {
            get {
                return ResourceManager.GetString("EmailProvider_HelpLinkText", resourceCulture);
            }
        }
        
        public static string EmailProvider_SendTestEmailMessage {
            get {
                return ResourceManager.GetString("EmailProvider_SendTestEmailMessage", resourceCulture);
            }
        }
        
        public static string EmailProvider_SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("EmailProvider_SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        public static string DeviceNotifications {
            get {
                return ResourceManager.GetString("DeviceNotifications", resourceCulture);
            }
        }
        
        public static string DeviceNotificationsDescription {
            get {
                return ResourceManager.GetString("DeviceNotificationsDescription", resourceCulture);
            }
        }
        
        public static string EsriApiKey {
            get {
                return ResourceManager.GetString("EsriApiKey", resourceCulture);
            }
        }
        
        public static string EsriApiKeyDescription {
            get {
                return ResourceManager.GetString("EsriApiKeyDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_Smtp {
            get {
                return ResourceManager.GetString("EmailProvider_Smtp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpDescription {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpDescription", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpHost {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpHost", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpHostHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpHostHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpPort {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpPort", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpPortHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpPortHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpTlsEncryption {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpTlsEncryption", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpTlsEncryptionHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpTlsEncryptionHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpAuthentication {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpAuthentication", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpAuthenticationHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpAuthenticationHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpUsername {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpUsername", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpUsernameHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpUsernameHelp", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpPassword {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpPassword", resourceCulture);
            }
        }
        
        public static string EmailProvider_SmtpPasswordHelp {
            get {
                return ResourceManager.GetString("EmailProvider_SmtpPasswordHelp", resourceCulture);
            }
        }
        
        public static string WorkspaceSettings {
            get {
                return ResourceManager.GetString("WorkspaceSettings", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        public static string GlobalNote {
            get {
                return ResourceManager.GetString("GlobalNote", resourceCulture);
            }
        }
        
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        public static string WebInterview {
            get {
                return ResourceManager.GetString("WebInterview", resourceCulture);
            }
        }
    }
}
