//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.UI.Headquarters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabletSyncMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabletSyncMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.UI.Headquarters.Resources.TabletSyncMessages", typeof(TabletSyncMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Android device id was not provided. Please contact developers..
        /// </summary>
        public static string AndroidDeviceIdWasNotProvided {
            get {
                return ResourceManager.GetString("AndroidDeviceIdWasNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. File with latest version was not found. Please contact developers..
        /// </summary>
        public static string FileWasNotFound {
            get {
                return ResourceManager.GetString("FileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Incorrect files count. Please contact developers..
        /// </summary>
        public static string IncorrectFilesCount {
            get {
                return ResourceManager.GetString("IncorrectFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Incorrect media type. Please contact developers..
        /// </summary>
        public static string IncorrectMediaType {
            get {
                return ResourceManager.GetString("IncorrectMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Your application is not compatible, please update your Interviewer app..
        /// </summary>
        public static string InterviewerApplicationShouldBeUpdated {
            get {
                return ResourceManager.GetString("InterviewerApplicationShouldBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Your application is not compatible. Uninstall your application and download new version of Interviewer app.
        /// </summary>
        public static string InterviewerIsNotCompatibleWithThisVersion {
            get {
                return ResourceManager.GetString("InterviewerIsNotCompatibleWithThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device identifier. Something has happened with the client app installation, please send tablet information..
        /// </summary>
        public static string InvalidDeviceIdentifier {
            get {
                return ResourceManager.GetString("InvalidDeviceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Invalid sequence identifier. Something has happened with the client app installation, press &quot;Send tablet information&quot; button..
        /// </summary>
        public static string InvalidSequenceIdentifier {
            get {
                return ResourceManager.GetString("InvalidSequenceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. User is not authorized. Please check your login/password for {0}..
        /// </summary>
        public static string InvalidUserFormat {
            get {
                return ResourceManager.GetString("InvalidUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have a role permitting this operation..
        /// </summary>
        public static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is on the maintenance mode now. Sorry for the inconvenience. Please, try again later..
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Please reinstall application. Installation identifier is missing. Please contact developers..
        /// </summary>
        public static string NoClientIdentifier {
            get {
                return ResourceManager.GetString("NoClientIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization partially failed. Completed interviews were sent to server, but you won&apos;t receive new assignments. Please navigate to android settings -&gt; Apps -&gt; Interviewer and push Clear Data button. Then synchronize from scratch..
        /// </summary>
        public static string OldInterviewerNeedsCleanup {
            get {
                return ResourceManager.GetString("OldInterviewerNeedsCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Internal server error occurred. Please contact developers..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.  Sync package with id &apos;{0}&apos; was not found on server. Please contact developers..
        /// </summary>
        public static string Sync_package_with_id__0__was_not_found_on_serverFormat {
            get {
                return ResourceManager.GetString("Sync_package_with_id__0__was_not_found_on_serverFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed. Wrong android device id was provided. Please contact developers..
        /// </summary>
        public static string WrongAndroidDeviceIdWasProvided {
            get {
                return ResourceManager.GetString("WrongAndroidDeviceIdWasProvided", resourceCulture);
            }
        }
    }
}
