using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using Humanizer;
using NHibernate;
using NHibernate.Cfg;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using NHibernate.Tool.hbm2ddl;
using Ninject;
using Ninject.Activation;
using Ninject.Web.Common;
using WB.Core.GenericSubdomains.Utils;
using WB.Core.Infrastructure.ReadSide.Repository.Accessors;
using WB.Core.Infrastructure.Storage.Memory.Implementation;
using WB.Core.Infrastructure.Storage.Postgre.Implementation;
using WB.Core.Infrastructure.Transactions;
using WB.Core.SharedKernels.SurveySolutions;

namespace WB.Core.Infrastructure.Storage.Postgre
{
    public class PostgresReadSideModule : Ninject.Modules.NinjectModule
    {
        internal const string ReadSideSessionFactoryName = "ReadSideSessionFactory";
        private readonly string connectionString;
        private readonly IEnumerable<Assembly> mappingAssemblies;

        public PostgresReadSideModule(string connectionString,
            IEnumerable<Assembly> mappingAssemblies)
        {
            this.connectionString = connectionString;
            this.mappingAssemblies = mappingAssemblies;
        }

        public override void Load()
        {
            this.Kernel.Bind<PostgreConnectionSettings>().ToConstant(new PostgreConnectionSettings{ConnectionString = connectionString });

            this.Kernel.Bind<IReadSideCleaner>().To<PostgresReadSideCleaner>();

            this.Kernel.Bind(typeof(PostgreReadSideRepository<>)).ToSelf().InSingletonScope();
            //this.Kernel.Bind(typeof(MemoryCachedReadSideRepositoryWriterProvider<>)).ToSelf();
            this.Kernel.Bind(typeof(IReadSideRepositoryWriter<>)).ToMethod(GetReadSideRepositoryWriter).InSingletonScope(); 
            
            this.Kernel.Bind<ISessionFactory>()
                       .ToMethod(kernel => this.BuildSessionFactory())
                       .InSingletonScope()
                       .Named(ReadSideSessionFactoryName);

            this.Kernel.Bind<CqrsPostgresCqrsTransactionManager>().ToSelf().InRequestScope();
            this.Kernel.Bind<Func<CqrsPostgresCqrsTransactionManager>>().ToMethod(context => () => context.Kernel.Get<CqrsPostgresCqrsTransactionManager>());
            this.Kernel.Bind<RebuildReadSideCqrsPostgresTransactionManager>().ToSelf();

            this.Kernel.Bind<TransactionManagerProvider>().ToSelf().InSingletonScope();

            this.Kernel.Bind<ISessionProvider>().ToMethod(context => context.Kernel.Get<TransactionManagerProvider>());
            this.Kernel.Bind<ITransactionManager>().To<CqrsPostgresCqrsTransactionManager>();

            this.Kernel.Bind<ITransactionManagerProvider>().ToMethod(context => context.Kernel.Get<TransactionManagerProvider>());
            this.Kernel.Bind<ITransactionManagerProviderManager>().ToMethod(context => context.Kernel.Get<TransactionManagerProvider>());

            this.Kernel.Bind(typeof (IQueryableReadSideRepositoryReader<>)).To(typeof (PostgreReadSideRepository<>));
            this.Kernel.Bind(typeof (IReadSideRepositoryReader<>)).To(typeof (PostgreReadSideRepository<>));

            //this.Kernel.Bind(typeof(IReadSideKeyValueStorage<>))
            //    .ToMethod(GetReadSideKeyValueStorage)
            //    .InSingletonScope();
        }

        private ISessionFactory BuildSessionFactory()
        {
            //File.WriteAllText(@"D:\Temp\Mapping.xml" ,Serialize(this.GetMappings()));
            var cfg = new Configuration();
            cfg.DataBaseIntegration(db =>
            {
                db.ConnectionString = connectionString;
                db.Dialect<NHibernate.Dialect.PostgreSQL82Dialect>();
                db.KeywordsAutoImport = Hbm2DDLKeyWords.AutoQuote;
            });
            cfg.Proxy(proxy => proxy.ProxyFactoryFactory<NHibernate.ByteCode.Castle.ProxyFactoryFactory>());

            cfg.AddDeserializedMapping(GetMappings(), "Main");
            var update = new SchemaUpdate(cfg);
            update.Execute(true, true);


            return cfg.BuildSessionFactory();
        }

        /// <summary>
        /// Generates XML string from <see cref="NHibernate"/> mappings. Used just to verify what was generated by ConfOrm to make sure everything is correct.
        /// </summary>
        protected static string Serialize(HbmMapping hbmElement)
        {
            var setting = new XmlWriterSettings { Indent = true };
            var serializer = new XmlSerializer(typeof(HbmMapping));
            using (var memStream = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(memStream, setting))
                {
                    serializer.Serialize(xmlWriter, hbmElement);
                    memStream.Flush();
                    byte[] streamContents = memStream.ToArray();

                    string result = Encoding.UTF8.GetString(streamContents);
                    return result;
                }
            }
        }

        private HbmMapping GetMappings()
        {
            var mapper = new ModelMapper();
            var mappingTypes = this.mappingAssemblies.SelectMany(x => x.GetExportedTypes())
                                                     .Where(x => x.IsSubclassOfRawGeneric(typeof(ClassMapping<>)));
            mapper.AddMappings(mappingTypes);
            mapper.BeforeMapProperty += (inspector, member, customizer) =>
            {
                var propertyInfo = (PropertyInfo) member.LocalMember;
                if (propertyInfo.PropertyType == typeof (string))
                {
                    customizer.Type(NHibernateUtil.StringClob);
                }
            };

            mapper.BeforeMapClass += (inspector, type, customizer) =>
            {
                var tableName = type.Name.Pluralize();
                customizer.Table(tableName);
            };

            return mapper.CompileMappingForAllExplicitlyAddedEntities();
        }

  

        private static object GetReadSideKeyValueStorage(IContext context)
        {
            //return context.Kernel.GetService(typeof (PostgreKeyValueStorage<>).MakeGenericType(context.GenericArguments[0]));

            var genericProvider = context.Kernel.Get(
                typeof(MemoryCachedKeyValueStorageProvider<>).MakeGenericType(context.GenericArguments[0])) as
                IProvider;

            if (genericProvider == null)
                return null;
            return genericProvider.Create(context);
        }

        private class MemoryCachedKeyValueStorageProvider<TEntity> : Provider<IReadSideKeyValueStorage<TEntity>>
            where TEntity : class, IReadSideRepositoryEntity
        {
            protected override IReadSideKeyValueStorage<TEntity> CreateInstance(IContext context)
            {
                return new MemoryCachedKeyValueStorage<TEntity>(context.Kernel.Get<PostgreKeyValueStorage<TEntity>>());
            }
        }

        private class MemoryCachedReadSideRepositoryWriterProvider<TEntity> : Provider<IReadSideRepositoryWriter<TEntity>>
       where TEntity : class, IReadSideRepositoryEntity
        {
            protected override IReadSideRepositoryWriter<TEntity> CreateInstance(IContext context)
            {
                return new MemoryCachedReadSideRepositoryWriter<TEntity>(context.Kernel.Get<PostgreReadSideRepository<TEntity>>());
            }
        }

        private static object GetReadSideRepositoryWriter(IContext context)
        {
//            return context.Kernel.GetService(typeof(PostgreReadSideRepository<>).MakeGenericType(context.GenericArguments[0]));

            var genericProvider = context.Kernel.Get(
                  typeof(MemoryCachedReadSideRepositoryWriterProvider<>).MakeGenericType(context.GenericArguments[0])) as
                  IProvider;

            if (genericProvider == null)
                return null;
            return genericProvider.Create(context);
        }
    }
}