//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.Core.BoundedContexts.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.Core.BoundedContexts.Designer.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question can&apos;t be linked and cascading at the same time..
        /// </summary>
        internal static string CantBeLinkedAndCascadingAtSameTime {
            get {
                return ResourceManager.GetString("CantBeLinkedAndCascadingAtSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question that is used as parent in cascading dropdowns cant be removed before all child questions are removed..
        /// </summary>
        internal static string CantRemoveParentQuestionInCascading {
            get {
                return ResourceManager.GetString("CantRemoveParentQuestionInCascading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-section or roster containing question that is used as parent for cascading combo box cannot be removed before all child questions are removed..
        /// </summary>
        internal static string CantRemoveSectionParentQuestionInCascading {
            get {
                return ResourceManager.GetString("CantRemoveSectionParentQuestionInCascading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading questions can&apos;t have enabling condition..
        /// </summary>
        internal static string CascadingCantHaveConditionExpression {
            get {
                return ResourceManager.GetString("CascadingCantHaveConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading questions can&apos;t have validation condition..
        /// </summary>
        internal static string CascadingCantHaveValidationExpression {
            get {
                return ResourceManager.GetString("CascadingCantHaveValidationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options in cascading question can not have empty ParentValue column..
        /// </summary>
        internal static string CategoricalCascadingOptionsCantContainsEmptyParentValueField {
            get {
                return ResourceManager.GetString("CategoricalCascadingOptionsCantContainsEmptyParentValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options in cascading question can not have not numeric value in ParentValue column..
        /// </summary>
        internal static string CategoricalCascadingOptionsCantContainsNotDecimalParentValueField {
            get {
                return ResourceManager.GetString("CategoricalCascadingOptionsCantContainsNotDecimalParentValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is at least one duplicate of Title + Parent Value pairs. List of options should not contain any duplicates of such type..
        /// </summary>
        internal static string CategoricalCascadingOptionsContainsNotUniqueTitleAndParentValuePair {
            get {
                return ResourceManager.GetString("CategoricalCascadingOptionsContainsNotUniqueTitleAndParentValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup table with such is is already exist..
        /// </summary>
        internal static string LookupTableAlreadyExist {
            get {
                return ResourceManager.GetString("LookupTableAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup table with such is is absent..
        /// </summary>
        internal static string LookupTableIsAbsent {
            get {
                return ResourceManager.GetString("LookupTableIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with no data can not be loaded.
        /// </summary>
        internal static string LookupTables_cant_has_empty_content {
            get {
                return ResourceManager.GetString("LookupTables_cant_has_empty_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} can not be parsed as decimal number. Column {1}, row {2}..
        /// </summary>
        internal static string LookupTables_data_value_cannot_be_parsed {
            get {
                return ResourceManager.GetString("LookupTables_data_value_cannot_be_parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty headers are not allowed.
        /// </summary>
        internal static string LookupTables_empty_header_are_not_allowed {
            get {
                return ResourceManager.GetString("LookupTables_empty_header_are_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory rowcode column is missing.
        /// </summary>
        internal static string LookupTables_rowcode_column_is_mandatory {
            get {
                return ResourceManager.GetString("LookupTables_rowcode_column_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} can not be parsed as long integer number. Column {1}, row {2}..
        /// </summary>
        internal static string LookupTables_rowcode_value_cannot_be_parsed {
            get {
                return ResourceManager.GetString("LookupTables_rowcode_value_cannot_be_parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many columns in uploaded file. Max coumns count is {0}.
        /// </summary>
        internal static string LookupTables_too_many_columns {
            get {
                return ResourceManager.GetString("LookupTables_too_many_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rows count limit ({0} rows) was exceeded..
        /// </summary>
        internal static string LookupTables_too_many_rows {
            get {
                return ResourceManager.GetString("LookupTables_too_many_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro with such is is already exist..
        /// </summary>
        internal static string MacroAlreadyExist {
            get {
                return ResourceManager.GetString("MacroAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro can not have empty content..
        /// </summary>
        internal static string MacroContentIsEmpty {
            get {
                return ResourceManager.GetString("MacroContentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro with such is is absent..
        /// </summary>
        internal static string MacroIsAbsent {
            get {
                return ResourceManager.GetString("MacroIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; from expression &apos;{1}&apos; is not valid question or roster identifier. Question or roster with such an identifier is missing..
        /// </summary>
        internal static string QuestionOrRosterIdentifierIsMissing {
            get {
                return ResourceManager.GetString("QuestionOrRosterIdentifierIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question to cascade from should exist in questionnaire..
        /// </summary>
        internal static string ShouldCascadeFromExistingQuestion {
            get {
                return ResourceManager.GetString("ShouldCascadeFromExistingQuestion", resourceCulture);
            }
        }
    }
}
