#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WB.UI.QuestionnaireTester.Resource", IsApplication=true)]

namespace WB.UI.QuestionnaireTester
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonoff = global::WB.UI.QuestionnaireTester.Resource.Drawable.flashbuttonoff;
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonon = global::WB.UI.QuestionnaireTester.Resource.Drawable.flashbuttonon;
			global::MWBarcodeScanner.Resource.Drawable.overlay = global::WB.UI.QuestionnaireTester.Resource.Drawable.overlay;
			global::MWBarcodeScanner.Resource.Id.RelativeLayout1 = global::WB.UI.QuestionnaireTester.Resource.Id.RelativeLayout1;
			global::MWBarcodeScanner.Resource.Id.flashButton = global::WB.UI.QuestionnaireTester.Resource.Id.flashButton;
			global::MWBarcodeScanner.Resource.Id.overlayImage = global::WB.UI.QuestionnaireTester.Resource.Id.overlayImage;
			global::MWBarcodeScanner.Resource.Id.preview_view = global::WB.UI.QuestionnaireTester.Resource.Id.preview_view;
			global::MWBarcodeScanner.Resource.Layout.scanner = global::WB.UI.QuestionnaireTester.Resource.Layout.scanner;
			global::MWBarcodeScanner.Resource.String.library_name = global::WB.UI.QuestionnaireTester.Resource.String.library_name;
			global::WB.Core.Infrastructure.Files.Resource.String.ApplicationName = global::WB.UI.QuestionnaireTester.Resource.String.ApplicationName;
			global::WB.Core.Infrastructure.Files.Resource.String.Hello = global::WB.UI.QuestionnaireTester.Resource.String.Hello;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxBind = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxBind;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxDropDownItemTemplate = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxDropDownItemTemplate;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxItemTemplate = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxItemTemplate;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxLang = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxLang;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxSource = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxSource;
			global::WB.UI.Shared.Android.Resource.Attribute.MvxTemplate = global::WB.UI.QuestionnaireTester.Resource.Attribute.MvxTemplate;
			global::WB.UI.Shared.Android.Resource.Color.capi_orange = global::WB.UI.QuestionnaireTester.Resource.Color.capi_orange;
			global::WB.UI.Shared.Android.Resource.Drawable.answer_progress_indicator = global::WB.UI.QuestionnaireTester.Resource.Drawable.answer_progress_indicator;
			global::WB.UI.Shared.Android.Resource.Drawable.bookmarkStyle = global::WB.UI.QuestionnaireTester.Resource.Drawable.bookmarkStyle;
			global::WB.UI.Shared.Android.Resource.Drawable.CounterRoundShape = global::WB.UI.QuestionnaireTester.Resource.Drawable.CounterRoundShape;
			global::WB.UI.Shared.Android.Resource.Drawable.donecountershape = global::WB.UI.QuestionnaireTester.Resource.Drawable.donecountershape;
			global::WB.UI.Shared.Android.Resource.Drawable.errorwarningstyle = global::WB.UI.QuestionnaireTester.Resource.Drawable.errorwarningstyle;
			global::WB.UI.Shared.Android.Resource.Drawable.flashbuttonoff = global::WB.UI.QuestionnaireTester.Resource.Drawable.flashbuttonoff;
			global::WB.UI.Shared.Android.Resource.Drawable.flashbuttonon = global::WB.UI.QuestionnaireTester.Resource.Drawable.flashbuttonon;
			global::WB.UI.Shared.Android.Resource.Drawable.grid_headerItem = global::WB.UI.QuestionnaireTester.Resource.Drawable.grid_headerItem;
			global::WB.UI.Shared.Android.Resource.Drawable.ic_drawer_dark = global::WB.UI.QuestionnaireTester.Resource.Drawable.ic_drawer_dark;
			global::WB.UI.Shared.Android.Resource.Drawable.infowarningstyle = global::WB.UI.QuestionnaireTester.Resource.Drawable.infowarningstyle;
			global::WB.UI.Shared.Android.Resource.Drawable.no_image_found = global::WB.UI.QuestionnaireTester.Resource.Drawable.no_image_found;
			global::WB.UI.Shared.Android.Resource.Drawable.overlay = global::WB.UI.QuestionnaireTester.Resource.Drawable.overlay;
			global::WB.UI.Shared.Android.Resource.Drawable.questionAnsweredShape = global::WB.UI.QuestionnaireTester.Resource.Drawable.questionAnsweredShape;
			global::WB.UI.Shared.Android.Resource.Drawable.questionDisabledShape = global::WB.UI.QuestionnaireTester.Resource.Drawable.questionDisabledShape;
			global::WB.UI.Shared.Android.Resource.Drawable.questionInvalidShape = global::WB.UI.QuestionnaireTester.Resource.Drawable.questionInvalidShape;
			global::WB.UI.Shared.Android.Resource.Drawable.questionShape = global::WB.UI.QuestionnaireTester.Resource.Drawable.questionShape;
			global::WB.UI.Shared.Android.Resource.Drawable.statistics_row_style = global::WB.UI.QuestionnaireTester.Resource.Drawable.statistics_row_style;
			global::WB.UI.Shared.Android.Resource.Id.AnswerId = global::WB.UI.QuestionnaireTester.Resource.Id.AnswerId;
			global::WB.UI.Shared.Android.Resource.Id.ElementId = global::WB.UI.QuestionnaireTester.Resource.Id.ElementId;
			global::WB.UI.Shared.Android.Resource.Id.Index = global::WB.UI.QuestionnaireTester.Resource.Id.Index;
			global::WB.UI.Shared.Android.Resource.Id.MvxBindingTagUnique = global::WB.UI.QuestionnaireTester.Resource.Id.MvxBindingTagUnique;
			global::WB.UI.Shared.Android.Resource.Id.MyLayout = global::WB.UI.QuestionnaireTester.Resource.Id.MyLayout;
			global::WB.UI.Shared.Android.Resource.Id.PrpagationKey = global::WB.UI.QuestionnaireTester.Resource.Id.PrpagationKey;
			global::WB.UI.Shared.Android.Resource.Id.QuestionnaireId = global::WB.UI.QuestionnaireTester.Resource.Id.QuestionnaireId;
			global::WB.UI.Shared.Android.Resource.Id.RelativeLayout1 = global::WB.UI.QuestionnaireTester.Resource.Id.RelativeLayout1;
			global::WB.UI.Shared.Android.Resource.Id.ScreenId = global::WB.UI.QuestionnaireTester.Resource.Id.ScreenId;
			global::WB.UI.Shared.Android.Resource.Id.btGroup = global::WB.UI.QuestionnaireTester.Resource.Id.btGroup;
			global::WB.UI.Shared.Android.Resource.Id.btnAnswered = global::WB.UI.QuestionnaireTester.Resource.Id.btnAnswered;
			global::WB.UI.Shared.Android.Resource.Id.btnComplete = global::WB.UI.QuestionnaireTester.Resource.Id.btnComplete;
			global::WB.UI.Shared.Android.Resource.Id.btnInstructions = global::WB.UI.QuestionnaireTester.Resource.Id.btnInstructions;
			global::WB.UI.Shared.Android.Resource.Id.btnInvalid = global::WB.UI.QuestionnaireTester.Resource.Id.btnInvalid;
			global::WB.UI.Shared.Android.Resource.Id.btnUnanswered = global::WB.UI.QuestionnaireTester.Resource.Id.btnUnanswered;
			global::WB.UI.Shared.Android.Resource.Id.etComments = global::WB.UI.QuestionnaireTester.Resource.Id.etComments;
			global::WB.UI.Shared.Android.Resource.Id.flashButton = global::WB.UI.QuestionnaireTester.Resource.Id.flashButton;
			global::WB.UI.Shared.Android.Resource.Id.llButtom = global::WB.UI.QuestionnaireTester.Resource.Id.llButtom;
			global::WB.UI.Shared.Android.Resource.Id.llContainer = global::WB.UI.QuestionnaireTester.Resource.Id.llContainer;
			global::WB.UI.Shared.Android.Resource.Id.llContent = global::WB.UI.QuestionnaireTester.Resource.Id.llContent;
			global::WB.UI.Shared.Android.Resource.Id.llNavigationHolder = global::WB.UI.QuestionnaireTester.Resource.Id.llNavigationHolder;
			global::WB.UI.Shared.Android.Resource.Id.llRoot = global::WB.UI.QuestionnaireTester.Resource.Id.llRoot;
			global::WB.UI.Shared.Android.Resource.Id.llTop = global::WB.UI.QuestionnaireTester.Resource.Id.llTop;
			global::WB.UI.Shared.Android.Resource.Id.llWrapper = global::WB.UI.QuestionnaireTester.Resource.Id.llWrapper;
			global::WB.UI.Shared.Android.Resource.Id.overlayImage = global::WB.UI.QuestionnaireTester.Resource.Id.overlayImage;
			global::WB.UI.Shared.Android.Resource.Id.preview_view = global::WB.UI.QuestionnaireTester.Resource.Id.preview_view;
			global::WB.UI.Shared.Android.Resource.Id.tvComments = global::WB.UI.QuestionnaireTester.Resource.Id.tvComments;
			global::WB.UI.Shared.Android.Resource.Id.tvCommentsTitle = global::WB.UI.QuestionnaireTester.Resource.Id.tvCommentsTitle;
			global::WB.UI.Shared.Android.Resource.Id.tvCount = global::WB.UI.QuestionnaireTester.Resource.Id.tvCount;
			global::WB.UI.Shared.Android.Resource.Id.tvCounterText = global::WB.UI.QuestionnaireTester.Resource.Id.tvCounterText;
			global::WB.UI.Shared.Android.Resource.Id.tvError = global::WB.UI.QuestionnaireTester.Resource.Id.tvError;
			global::WB.UI.Shared.Android.Resource.Id.tvErrorWarning = global::WB.UI.QuestionnaireTester.Resource.Id.tvErrorWarning;
			global::WB.UI.Shared.Android.Resource.Id.tvITem = global::WB.UI.QuestionnaireTester.Resource.Id.tvITem;
			global::WB.UI.Shared.Android.Resource.Id.tvMError = global::WB.UI.QuestionnaireTester.Resource.Id.tvMError;
			global::WB.UI.Shared.Android.Resource.Id.tvText = global::WB.UI.QuestionnaireTester.Resource.Id.tvText;
			global::WB.UI.Shared.Android.Resource.Id.tvTitle = global::WB.UI.QuestionnaireTester.Resource.Id.tvTitle;
			global::WB.UI.Shared.Android.Resource.Id.vpContent = global::WB.UI.QuestionnaireTester.Resource.Id.vpContent;
			global::WB.UI.Shared.Android.Resource.Layout.AbstractQuestionView = global::WB.UI.QuestionnaireTester.Resource.Layout.AbstractQuestionView;
			global::WB.UI.Shared.Android.Resource.Layout.CascadingComboboxRowLayout = global::WB.UI.QuestionnaireTester.Resource.Layout.CascadingComboboxRowLayout;
			global::WB.UI.Shared.Android.Resource.Layout.Details = global::WB.UI.QuestionnaireTester.Resource.Layout.Details;
			global::WB.UI.Shared.Android.Resource.Layout.FilteredComboboxRowLayout = global::WB.UI.QuestionnaireTester.Resource.Layout.FilteredComboboxRowLayout;
			global::WB.UI.Shared.Android.Resource.Layout.GroupView = global::WB.UI.QuestionnaireTester.Resource.Layout.GroupView;
			global::WB.UI.Shared.Android.Resource.Layout.list_navigation_item = global::WB.UI.QuestionnaireTester.Resource.Layout.list_navigation_item;
			global::WB.UI.Shared.Android.Resource.Layout.RosterQuestion = global::WB.UI.QuestionnaireTester.Resource.Layout.RosterQuestion;
			global::WB.UI.Shared.Android.Resource.Layout.scanner = global::WB.UI.QuestionnaireTester.Resource.Layout.scanner;
			global::WB.UI.Shared.Android.Resource.Layout.ScreenContentFragment = global::WB.UI.QuestionnaireTester.Resource.Layout.ScreenContentFragment;
			global::WB.UI.Shared.Android.Resource.Layout.StaticTextView = global::WB.UI.QuestionnaireTester.Resource.Layout.StaticTextView;
			global::WB.UI.Shared.Android.Resource.Layout.StatisticsContent = global::WB.UI.QuestionnaireTester.Resource.Layout.StatisticsContent;
			global::WB.UI.Shared.Android.Resource.String.AnswerIsNotPresentInFilteredComboboxOptionsList = global::WB.UI.QuestionnaireTester.Resource.String.AnswerIsNotPresentInFilteredComboboxOptionsList;
			global::WB.UI.Shared.Android.Resource.String.ApplicationName = global::WB.UI.QuestionnaireTester.Resource.String.ApplicationName;
			global::WB.UI.Shared.Android.Resource.String.AreYouSureYouWantToRemoveRowFromRosterFormat = global::WB.UI.QuestionnaireTester.Resource.String.AreYouSureYouWantToRemoveRowFromRosterFormat;
			global::WB.UI.Shared.Android.Resource.String.No = global::WB.UI.QuestionnaireTester.Resource.String.No;
			global::WB.UI.Shared.Android.Resource.String.SendingOfInformationPackageIsCanceling = global::WB.UI.QuestionnaireTester.Resource.String.SendingOfInformationPackageIsCanceling;
			global::WB.UI.Shared.Android.Resource.String.Warning = global::WB.UI.QuestionnaireTester.Resource.String.Warning;
			global::WB.UI.Shared.Android.Resource.String.Yes = global::WB.UI.QuestionnaireTester.Resource.String.Yes;
			global::WB.UI.Shared.Android.Resource.String.drawer_close = global::WB.UI.QuestionnaireTester.Resource.String.drawer_close;
			global::WB.UI.Shared.Android.Resource.String.drawer_open = global::WB.UI.QuestionnaireTester.Resource.String.drawer_open;
			global::WB.UI.Shared.Android.Resource.String.library_name = global::WB.UI.QuestionnaireTester.Resource.String.library_name;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxBinding = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxBinding;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxBinding_MvxBind = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxBinding_MvxBind;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxBinding_MvxLang = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxBinding_MvxLang;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxControl = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxControl;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxControl_MvxTemplate = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxControl_MvxTemplate;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxImageView = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxImageView;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxImageView_MvxSource = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxImageView_MvxSource;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxListView = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxListView;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::WB.UI.Shared.Android.Resource.Styleable.MvxListView_MvxItemTemplate = global::WB.UI.QuestionnaireTester.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int capi_orange = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int answer_progress_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bookmarkStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int capi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CounterRoundShape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int donecountershape = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int errorwarningstyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flashbuttonoff = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flashbuttonon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int grid_headerItem = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_drawer_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int infowarningstyle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int no_image_found = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int overlay = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int questionAnsweredShape = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int questionDisabledShape = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int questionInvalidShape = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int questionShape = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int statistics_row_style = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tester_icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tester_splash = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int AnswerId = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int ElementId = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Index = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int MyLayout = 2131034138;
			
			// aapt resource value: 0x7f050003
			public const int PrpagationKey = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int QuestionnaireId = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int QuestionnaireTitle = 2131034119;
			
			// aapt resource value: 0x7f05002a
			public const int RelativeLayout1 = 2131034154;
			
			// aapt resource value: 0x7f050002
			public const int ScreenId = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int btGroup = 2131034139;
			
			// aapt resource value: 0x7f050032
			public const int btnAnswered = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int btnComplete = 2131034166;
			
			// aapt resource value: 0x7f050009
			public const int btnInstructions = 2131034121;
			
			// aapt resource value: 0x7f050035
			public const int btnInvalid = 2131034165;
			
			// aapt resource value: 0x7f050026
			public const int btnLogin = 2131034150;
			
			// aapt resource value: 0x7f050013
			public const int btnLogout = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int btnNext = 2131034134;
			
			// aapt resource value: 0x7f050029
			public const int btnSave = 2131034153;
			
			// aapt resource value: 0x7f05001d
			public const int btnStart = 2131034141;
			
			// aapt resource value: 0x7f050033
			public const int btnUnanswered = 2131034163;
			
			// aapt resource value: 0x7f050010
			public const int etComments = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int flFragmentHolder = 2131034133;
			
			// aapt resource value: 0x7f05002d
			public const int flashButton = 2131034157;
			
			// aapt resource value: 0x7f050022
			public const int footer = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int header = 2131034145;
			
			// aapt resource value: 0x7f050011
			public const int imgAnswerProgress = 2131034129;
			
			// aapt resource value: 0x7f050030
			public const int llButtom = 2131034160;
			
			// aapt resource value: 0x7f050017
			public const int llContainer = 2131034135;
			
			// aapt resource value: 0x7f05002f
			public const int llContent = 2131034159;
			
			// aapt resource value: 0x7f050027
			public const int llDesignerPath = 2131034151;
			
			// aapt resource value: 0x7f050019
			public const int llNavigationHolder = 2131034137;
			
			// aapt resource value: 0x7f050037
			public const int llQuestionnairie = 2131034167;
			
			// aapt resource value: 0x7f050008
			public const int llRoot = 2131034120;
			
			// aapt resource value: 0x7f05002e
			public const int llTop = 2131034158;
			
			// aapt resource value: 0x7f05000a
			public const int llWrapper = 2131034122;
			
			// aapt resource value: 0x7f050023
			public const int loginForm = 2131034147;
			
			// aapt resource value: 0x7f05002c
			public const int overlayImage = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int preview_view = 2131034155;
			
			// aapt resource value: 0x7f050014
			public const int svQuery = 2131034132;
			
			// aapt resource value: 0x7f050024
			public const int teLogin = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int tePassword = 2131034149;
			
			// aapt resource value: 0x7f050028
			public const int tePathToDesigner = 2131034152;
			
			// aapt resource value: 0x7f050020
			public const int topView = 2131034144;
			
			// aapt resource value: 0x7f050038
			public const int tvArrow = 2131034168;
			
			// aapt resource value: 0x7f05000e
			public const int tvComments = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tvCommentsTitle = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int tvCount = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int tvCounterText = 2131034140;
			
			// aapt resource value: 0x7f05000c
			public const int tvError = 2131034124;
			
			// aapt resource value: 0x7f050034
			public const int tvErrorWarning = 2131034164;
			
			// aapt resource value: 0x7f05001e
			public const int tvITem = 2131034142;
			
			// aapt resource value: 0x7f05000b
			public const int tvMError = 2131034123;
			
			// aapt resource value: 0x7f050031
			public const int tvText = 2131034161;
			
			// aapt resource value: 0x7f05000d
			public const int tvTitle = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int tvTitlte = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int vpContent = 2131034136;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AbstractQuestionView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionBar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActionBarSearchable = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CascadingComboboxRowLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateInterview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Details = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FilteredComboboxRowLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GroupView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Home = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int list_navigation_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RosterQuestion = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int scanner = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ScreenContentFragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SplashScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int StaticTextView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int StatisticsContent = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int template_list_item = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int AnswerIsNotPresentInFilteredComboboxOptionsList = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int AreYouSureYouWantToRemoveRowFromRosterFormat = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int DesignerPath = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int Hello = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int No = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int Oops = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int QuestionnaireLoadingError = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int ReasonFormat = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int SendingOfInformationPackageIsCanceling = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int TemplateIsMissing = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int TemplateIsNotValidForCurrentVersionOfTester = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int Warning = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Yes = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int drawer_close = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int drawer_open = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int library_name = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_SplashBackground = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
