namespace WB.Core.SharedKernels.SurveyManagement.Web.Models
{
    public enum MenuItem
    {
        Surveys = 0,
        Interviewers = 1,
        Statuses = 2,
        Docs = 3,
        Logon = 4,
        Devices = 5,
        SyncLog = 6,
        Teams = 7,
        Summary = 8,
        Questionnaires = 9,
        MapReport = 10,
        InterviewsChart = 11,
        ManageAccount = 12,
        Headquarters = 13,
        Observers = 14,
        NumberOfCompletedInterviews = 15,
        DataExport = 16,
        SpeedOfCompletingInterviews = 17,
        UserBatchUpload = 18,
        ApiUsers = 19,
        Settings = 20,
        Assignments = 22,
        CreateNew = 23,
        Started = 24,
        Rejected = 25,
        Completed = 26,
        Profile = 27,
        DevicesInterviewers = 28,
        StatusDuration = 29,
        SurveyAndStatuses = 30,
        AuditLog = 31,
        Maps = 32,
        TeamMembersAndStatuses = 33,
        SurveyStatistics = 34,
        EmailProviders = 35,
        Interviews = 36,
        TabletLogs = 37,
        Administration_TabletInfo = 38,
        Administration_Config = 39,
        Administration_AppUpdates = 40,
        Administration_InterviewPackages = 41,
        Administration_Exceptions = 42,
        Administration_CreateAdmin = 43,
        Administration_ChangePassword = 44,
        Administration_ReevaluateInterview = 45,
        ChangePassword = 46,
        Administration_Diagnostics = 40,
        Workspaces = 47,
        ServerAdministration = 48,
        UsersManagement = 49,
        MapDashboard = 50
    }
}
