//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.UI.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuestionnaireEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionnaireEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.UI.Designer.Resources.QuestionnaireEditor", typeof(QuestionnaireEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new section.
        /// </summary>
        internal static string AddNewSection {
            get {
                return ResourceManager.GetString("AddNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        internal static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add roster.
        /// </summary>
        internal static string AddRoster {
            get {
                return ResourceManager.GetString("AddRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add static text.
        /// </summary>
        internal static string AddStaticText {
            get {
                return ResourceManager.GetString("AddStaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub-section.
        /// </summary>
        internal static string AddSubsection {
            get {
                return ResourceManager.GetString("AddSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new validation rule.
        /// </summary>
        internal static string AddValidationRule {
            get {
                return ResourceManager.GetString("AddValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variable.
        /// </summary>
        internal static string AddVariable {
            get {
                return ResourceManager.GetString("AddVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment preview.
        /// </summary>
        internal static string AttachmentPreview {
            get {
                return ResourceManager.GetString("AttachmentPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} error found.
        /// </summary>
        internal static string CompilationErrorsCounter {
            get {
                return ResourceManager.GetString("CompilationErrorsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} errors found.
        /// </summary>
        internal static string CompilationErrorsCounter_plural {
            get {
                return ResourceManager.GetString("CompilationErrorsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation:.
        /// </summary>
        internal static string CompilationLabel {
            get {
                return ResourceManager.GetString("CompilationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} warning found.
        /// </summary>
        internal static string CompilationWarningsCounter {
            get {
                return ResourceManager.GetString("CompilationWarningsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} warnings found.
        /// </summary>
        internal static string CompilationWarningsCounter_plural {
            get {
                return ResourceManager.GetString("CompilationWarningsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition or cascading depended items might be broken.
        /// </summary>
        internal static string ConditionMightBeBroken {
            get {
                return ResourceManager.GetString("ConditionMightBeBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is empty..
        /// </summary>
        internal static string EmptySectionLine1 {
            get {
                return ResourceManager.GetString("EmptySectionLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start by using {{-addQuestionBtn}} and {{-addSubsectionBtn}} buttons.
        /// </summary>
        internal static string EmptySectionLine2 {
            get {
                return ResourceManager.GetString("EmptySectionLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on top of this block or manage sections with {{-panel}} left panel.
        /// </summary>
        internal static string EmptySectionLine3 {
            get {
                return ResourceManager.GetString("EmptySectionLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of survey, device types, collaboration and other options.
        /// </summary>
        internal static string EmptySectionLine4 {
            get {
                return ResourceManager.GetString("EmptySectionLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can be found at {{-settingsBtn}} panel (top right corner).
        /// </summary>
        internal static string EmptySectionLine5 {
            get {
                return ResourceManager.GetString("EmptySectionLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling condition.
        /// </summary>
        internal static string EnablingCondition {
            get {
                return ResourceManager.GetString("EnablingCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered more than maximum allowed {{max}}.
        /// </summary>
        internal static string EnteredMoreThanAllowed {
            get {
                return ResourceManager.GetString("EnteredMoreThanAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} error.
        /// </summary>
        internal static string ErrorsCounter {
            get {
                return ResourceManager.GetString("ErrorsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} errors.
        /// </summary>
        internal static string ErrorsCounter_plural {
            get {
                return ResourceManager.GetString("ErrorsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search.
        /// </summary>
        internal static string FindReplaceBackToSearch {
            get {
                return ResourceManager.GetString("FindReplaceBackToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string FindReplaceDone {
            get {
                return ResourceManager.GetString("FindReplaceDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all.
        /// </summary>
        internal static string FindReplaceFindAll {
            get {
                return ResourceManager.GetString("FindReplaceFindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        internal static string FindReplaceFindWhat {
            get {
                return ResourceManager.GetString("FindReplaceFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FindReplaceInAll {
            get {
                return ResourceManager.GetString("FindReplaceInAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {{count}} found entity?.
        /// </summary>
        internal static string FindReplaceInAllFound {
            get {
                return ResourceManager.GetString("FindReplaceInAllFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {{count}} found entities?.
        /// </summary>
        internal static string FindReplaceInAllFound_plural {
            get {
                return ResourceManager.GetString("FindReplaceInAllFound_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string FindReplaceMatchCase {
            get {
                return ResourceManager.GetString("FindReplaceMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching lines: {{count}}.
        /// </summary>
        internal static string FindReplaceMatchingLines {
            get {
                return ResourceManager.GetString("FindReplaceMatchingLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        internal static string FindReplaceMatchWord {
            get {
                return ResourceManager.GetString("FindReplaceMatchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string FindReplaceNext {
            get {
                return ResourceManager.GetString("FindReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string FindReplacePrevious {
            get {
                return ResourceManager.GetString("FindReplacePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all ({{count}}).
        /// </summary>
        internal static string FindReplaceReplaceAll {
            get {
                return ResourceManager.GetString("FindReplaceReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all .
        /// </summary>
        internal static string FindReplaceReplaceAllConfirm {
            get {
                return ResourceManager.GetString("FindReplaceReplaceAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string FindReplaceReplaceAllConfirmWith {
            get {
                return ResourceManager.GetString("FindReplaceReplaceAllConfirmWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string FindReplaceReplaceWith {
            get {
                return ResourceManager.GetString("FindReplaceReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace.
        /// </summary>
        internal static string FindReplaceTitle {
            get {
                return ResourceManager.GetString("FindReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expression.
        /// </summary>
        internal static string FindReplaceUseRegex {
            get {
                return ResourceManager.GetString("FindReplaceUseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to were replaced with.
        /// </summary>
        internal static string FindReplaceWereReplaced {
            get {
                return ResourceManager.GetString("FindReplaceWereReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm action..
        /// </summary>
        internal static string FindReplaceСonfirm {
            get {
                return ResourceManager.GetString("FindReplaceСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {{currentUserName}}.
        /// </summary>
        internal static string HellowMessageBtn {
            get {
                return ResourceManager.GetString("HellowMessageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logical expression that activates(deactivates) the current item depending on the answers on the other questions..
        /// </summary>
        internal static string HelpConditionExpression {
            get {
                return ResourceManager.GetString("HelpConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logical expression that is calculated depending on the answers on the other questions..
        /// </summary>
        internal static string HelpExpression {
            get {
                return ResourceManager.GetString("HelpExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items determines the roster size. Each element of the list corresponds to a title of the roster row. Each element of the list should be placed on a separate line..
        /// </summary>
        internal static string HelpFixedTitles {
            get {
                return ResourceManager.GetString("HelpFixedTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, a disabled item is greyed-out. Checking this option will hide a disabled question or section on a tablet..
        /// </summary>
        internal static string HelpHideIfDisabled {
            get {
                return ResourceManager.GetString("HelpHideIfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, an instruction text is shown on a tablet. Checking this option will show only the first line of instructions. Tapping on that line will show the complete text..
        /// </summary>
        internal static string HelpHideInstructions {
            get {
                return ResourceManager.GetString("HelpHideInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction text that will be attached to the question..
        /// </summary>
        internal static string HelpInstruction {
            get {
                return ResourceManager.GetString("HelpInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows the user to stamp the current time on tablet.
        /// </summary>
        internal static string HelpIsTimestamp {
            get {
                return ResourceManager.GetString("HelpIsTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted entry for alpha-numerical values: phone numbers, ID codes, etc. Examples:&quot;~&quot; - Represents an alpha character (A-Z,a-z), &quot;#&quot; - Represents a numeric character (0-9), &quot;*&quot; - Represents an alphanumeric character (A-Z,a-z,0-9). &quot;##/##/####&quot; - date, &quot;(###) ###-####&quot; - phone number, &quot;AA####&quot; - flight number operated by American AirLines or &quot;~*-###-~###&quot;.
        /// </summary>
        internal static string HelpMask {
            get {
                return ResourceManager.GetString("HelpMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source question (answer generates number of rows).
        /// </summary>
        internal static string HelpSourceQuestion {
            get {
                return ResourceManager.GetString("HelpSourceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles of rows..
        /// </summary>
        internal static string HelpTitles {
            get {
                return ResourceManager.GetString("HelpTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the numeric field on the tablet will be formatted as: d,ddd,ddd.dd, &quot;d&quot; represents digits (0-9), “,”(comma) is a thousand separator, and &quot;.&quot; (dot) is a decimal point symbol.  Thousand separator and the decimal point symbol may vary for tablets with different cultures..
        /// </summary>
        internal static string HelpUseFormatting {
            get {
                return ResourceManager.GetString("HelpUseFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logical expression that validates an answer to the current question. Might include values of other questions..
        /// </summary>
        internal static string HelpValidationExpression {
            get {
                return ResourceManager.GetString("HelpValidationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message is shown when validation condition evaluates to &quot;False&quot; or error occurres during expression evaluation..
        /// </summary>
        internal static string HelpValidationMessage {
            get {
                return ResourceManager.GetString("HelpValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text that will be shown next to a variable for testing purposes.
        /// </summary>
        internal static string HelpVariableDescription {
            get {
                return ResourceManager.GetString("HelpVariableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text up to 80 characters that will be attached to the exported variable..
        /// </summary>
        internal static string HelpVariableLabel {
            get {
                return ResourceManager.GetString("HelpVariableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names and roster IDs may be from {{minLength}} to {{maxLength}} characters long and must contain only following characters: a-z, A-Z, _, or 0-9. The first character cannot be 0-9 or _ and the last one cannot be _..
        /// </summary>
        internal static string HelpVariableName {
            get {
                return ResourceManager.GetString("HelpVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide if disabled.
        /// </summary>
        internal static string HideIfDisabled {
            get {
                return ResourceManager.GetString("HideIfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close lookup tables panel.
        /// </summary>
        internal static string HotkeysCloseLookup {
            get {
                return ResourceManager.GetString("HotkeysCloseLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close macros panel.
        /// </summary>
        internal static string HotkeysCloseMacros {
            get {
                return ResourceManager.GetString("HotkeysCloseMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close translations panel.
        /// </summary>
        internal static string HotkeysCloseTranslations {
            get {
                return ResourceManager.GetString("HotkeysCloseTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus title field in editor.
        /// </summary>
        internal static string HotkeysFocusTitle {
            get {
                return ResourceManager.GetString("HotkeysFocusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus questionnaire tree.
        /// </summary>
        internal static string HotkeysFocusTree {
            get {
                return ResourceManager.GetString("HotkeysFocusTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close attachments panel.
        /// </summary>
        internal static string HotkeysHideAttachments {
            get {
                return ResourceManager.GetString("HotkeysHideAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close sections.
        /// </summary>
        internal static string HotkeysHideSections {
            get {
                return ResourceManager.GetString("HotkeysHideSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to previous sibling.
        /// </summary>
        internal static string HotkeysNavigateToPrevSibling {
            get {
                return ResourceManager.GetString("HotkeysNavigateToPrevSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to next sibling.
        /// </summary>
        internal static string HotkeysNavigateToSibling {
            get {
                return ResourceManager.GetString("HotkeysNavigateToSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open item in editor.
        /// </summary>
        internal static string HotkeysOpenItem {
            get {
                return ResourceManager.GetString("HotkeysOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open section.
        /// </summary>
        internal static string HotkeysOpenSection {
            get {
                return ResourceManager.GetString("HotkeysOpenSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string HotkeysPrint {
            get {
                return ResourceManager.GetString("HotkeysPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for sub-sections and questions in section.
        /// </summary>
        internal static string HotkeysSearch {
            get {
                return ResourceManager.GetString("HotkeysSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ModalConfirm {
            get {
                return ResourceManager.GetString("ModalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ModalInfo {
            get {
                return ResourceManager.GetString("ModalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        internal static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to another sub-section:.
        /// </summary>
        internal static string MoveToAnotherSubSection {
            get {
                return ResourceManager.GetString("MoveToAnotherSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more questions/sub-sections depend on.
        /// </summary>
        internal static string MultipleDependencies {
            get {
                return ResourceManager.GetString("MultipleDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions for changing this questionnaire.
        /// </summary>
        internal static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen file is not image.
        /// </summary>
        internal static string NotAnImage {
            get {
                return ResourceManager.GetString("NotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid input. Each line should follow the format: &quot;Title...Value&quot;. &apos;Value&apos; must be an integer number. Title must be an alpha-numeric string. No empty lines are allowed..
        /// </summary>
        internal static string OptionsListError {
            get {
                return ResourceManager.GetString("OptionsListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste after.
        /// </summary>
        internal static string PasteAfter {
            get {
                return ResourceManager.GetString("PasteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Interviewer Instruction.
        /// </summary>
        internal static string QuestionAddInstruction {
            get {
                return ResourceManager.GetString("QuestionAddInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add option.
        /// </summary>
        internal static string QuestionAddOption {
            get {
                return ResourceManager.GetString("QuestionAddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading combo box.
        /// </summary>
        internal static string QuestionCascading {
            get {
                return ResourceManager.GetString("QuestionCascading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click reload.
        /// </summary>
        internal static string QuestionClickReload {
            get {
                return ResourceManager.GetString("QuestionClickReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box.
        /// </summary>
        internal static string QuestionComboBox {
            get {
                return ResourceManager.GetString("QuestionComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time.
        /// </summary>
        internal static string QuestionCurrentTime {
            get {
                return ResourceManager.GetString("QuestionCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decimal places.
        /// </summary>
        internal static string QuestionDecimalPlaces {
            get {
                return ResourceManager.GetString("QuestionDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string QuestionFilter {
            get {
                return ResourceManager.GetString("QuestionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question will be treated as GPS navigation question for Interviewer.
        /// </summary>
        internal static string QuestionGpsNavigation {
            get {
                return ResourceManager.GetString("QuestionGpsNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide instruction.
        /// </summary>
        internal static string QuestionHideInstruction {
            get {
                return ResourceManager.GetString("QuestionHideInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        internal static string QuestionInstruction {
            get {
                return ResourceManager.GetString("QuestionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string QuestionInteger {
            get {
                return ResourceManager.GetString("QuestionInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is linked.
        /// </summary>
        internal static string QuestionIsLinked {
            get {
                return ResourceManager.GetString("QuestionIsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to list question or question from roster group.
        /// </summary>
        internal static string QuestionLinkedDescr {
            get {
                return ResourceManager.GetString("QuestionLinkedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of list elements.
        /// </summary>
        internal static string QuestionMaxListCount {
            get {
                return ResourceManager.GetString("QuestionMaxListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of answers.
        /// </summary>
        internal static string QuestionMaxNumberOfAnswers {
            get {
                return ResourceManager.GetString("QuestionMaxNumberOfAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must bind this question.
        /// </summary>
        internal static string QuestionMustBeBound {
            get {
                return ResourceManager.GetString("QuestionMustBeBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({{questionsCount}}Q, {{groupsCount}}S, {{rostersCount}}R).
        /// </summary>
        internal static string QuestionnaireSummary {
            get {
                return ResourceManager.GetString("QuestionnaireSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only integers are allowed.
        /// </summary>
        internal static string QuestionOnlyInts {
            get {
                return ResourceManager.GetString("QuestionOnlyInts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open options editor all unsaved changes must be saved. Should we save them now?.
        /// </summary>
        internal static string QuestionOpenEditorConfirm {
            get {
                return ResourceManager.GetString("QuestionOpenEditorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was saved successfully. The window for file upload will be opened..
        /// </summary>
        internal static string QuestionOpenEditorSaved {
            get {
                return ResourceManager.GetString("QuestionOpenEditorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the question was marked as &quot;Combo box&quot; or &quot;Cascading combo box&quot; while uploading question&apos;s details and contained many options, it&apos;s value was reduced up to {{count}}.
        /// </summary>
        internal static string QuestionOptionsCut {
            get {
                return ResourceManager.GetString("QuestionOptionsCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record answer order.
        /// </summary>
        internal static string QuestionOrdered {
            get {
                return ResourceManager.GetString("QuestionOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string QuestionPattern {
            get {
                return ResourceManager.GetString("QuestionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        internal static string QuestionQuestionType {
            get {
                return ResourceManager.GetString("QuestionQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question scope.
        /// </summary>
        internal static string QuestionScope {
            get {
                return ResourceManager.GetString("QuestionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show strings.
        /// </summary>
        internal static string QuestionShowStrings {
            get {
                return ResourceManager.GetString("QuestionShowStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To update options.
        /// </summary>
        internal static string QuestionToUpdateOptions {
            get {
                return ResourceManager.GetString("QuestionToUpdateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new options.
        /// </summary>
        internal static string QuestionUploadOptions {
            get {
                return ResourceManager.GetString("QuestionUploadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 1000 separator.
        /// </summary>
        internal static string QuestionUseSeparator {
            get {
                return ResourceManager.GetString("QuestionUseSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable label.
        /// </summary>
        internal static string QuestionVariableLabel {
            get {
                return ResourceManager.GetString("QuestionVariableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name.
        /// </summary>
        internal static string QuestionVariableName {
            get {
                return ResourceManager.GetString("QuestionVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No mode.
        /// </summary>
        internal static string QuestionYesNoMode {
            get {
                return ResourceManager.GetString("QuestionYesNoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recompile.
        /// </summary>
        internal static string Recompile {
            get {
                return ResourceManager.GetString("Recompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        internal static string RosterAddItem {
            get {
                return ResourceManager.GetString("RosterAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster name.
        /// </summary>
        internal static string RosterName {
            get {
                return ResourceManager.GetString("RosterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show strings.
        /// </summary>
        internal static string RosterShowStrings {
            get {
                return ResourceManager.GetString("RosterShowStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster source.
        /// </summary>
        internal static string RosterSource {
            get {
                return ResourceManager.GetString("RosterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed set of items:.
        /// </summary>
        internal static string RosterSourceFixed {
            get {
                return ResourceManager.GetString("RosterSourceFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source question for number of rows:.
        /// </summary>
        internal static string RosterSourceNumericQuestion {
            get {
                return ResourceManager.GetString("RosterSourceNumericQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source question for names of rows:.
        /// </summary>
        internal static string RosterSourceNumericTitles {
            get {
                return ResourceManager.GetString("RosterSourceNumericTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source question (answer determines both the number and the name of roster rows):.
        /// </summary>
        internal static string RosterSourceQuestion {
            get {
                return ResourceManager.GetString("RosterSourceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster ID.
        /// </summary>
        internal static string RosterVariableName {
            get {
                return ResourceManager.GetString("RosterVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved at {{dateTime, H:mm}}.
        /// </summary>
        internal static string SavedAtTimestamp {
            get {
                return ResourceManager.GetString("SavedAtTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parent question.
        /// </summary>
        internal static string SelectParentQuestion {
            get {
                return ResourceManager.GetString("SelectParentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the parent question.
        /// </summary>
        internal static string SelectParentQuestionError {
            get {
                return ResourceManager.GetString("SelectParentQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question.
        /// </summary>
        internal static string SelectQuestion {
            get {
                return ResourceManager.GetString("SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can .
        /// </summary>
        internal static string SettingsCan {
            get {
                return ResourceManager.GetString("SettingsCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string SettingsInvite {
            get {
                return ResourceManager.GetString("SettingsInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite collaborators by e-mail:.
        /// </summary>
        internal static string SettingsInviteCollaborators {
            get {
                return ResourceManager.GetString("SettingsInviteCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner.
        /// </summary>
        internal static string SettingsOwner {
            get {
                return ResourceManager.GetString("SettingsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string SettingsPrivate {
            get {
                return ResourceManager.GetString("SettingsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide email of existing user.
        /// </summary>
        internal static string SettingsProvideExistingEmail {
            get {
                return ResourceManager.GetString("SettingsProvideExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid email.
        /// </summary>
        internal static string SettingsProvideValidEmail {
            get {
                return ResourceManager.GetString("SettingsProvideValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string SettingsPublic {
            get {
                return ResourceManager.GetString("SettingsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire name:.
        /// </summary>
        internal static string SettingsQuestionnaireName {
            get {
                return ResourceManager.GetString("SettingsQuestionnaireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make this questionnaire.
        /// </summary>
        internal static string SettingsQuestionnaireSharing {
            get {
                return ResourceManager.GetString("SettingsQuestionnaireSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke access.
        /// </summary>
        internal static string SettingsRevokeAccess {
            get {
                return ResourceManager.GetString("SettingsRevokeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visible to everyone in read only mode.
        /// </summary>
        internal static string SettingsVisibleToEveryone {
            get {
                return ResourceManager.GetString("SettingsVisibleToEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visible to owner only.
        /// </summary>
        internal static string SettingsVisibleToOwner {
            get {
                return ResourceManager.GetString("SettingsVisibleToOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who has access:.
        /// </summary>
        internal static string SettingsWhoHasAccess {
            get {
                return ResourceManager.GetString("SettingsWhoHasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list.
        /// </summary>
        internal static string ShowList {
            get {
                return ResourceManager.GetString("ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new Macro.
        /// </summary>
        internal static string SideBarAddMacro {
            get {
                return ResourceManager.GetString("SideBarAddMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format: {{- type}}.
        /// </summary>
        internal static string SideBarAttachmentDetailsFormat {
            get {
                return ResourceManager.GetString("SideBarAttachmentDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{width}} × {{height}}px.
        /// </summary>
        internal static string SideBarAttachmentDetailsResolution {
            get {
                return ResourceManager.GetString("SideBarAttachmentDetailsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size: {{size}}.
        /// </summary>
        internal static string SideBarAttachmentDetailsSize {
            get {
                return ResourceManager.GetString("SideBarAttachmentDetailsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment name.
        /// </summary>
        internal static string SideBarAttachmentName {
            get {
                return ResourceManager.GetString("SideBarAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} File Attachment ({{bytes}} total).
        /// </summary>
        internal static string SideBarAttachmentsCounter {
            get {
                return ResourceManager.GetString("SideBarAttachmentsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Files Attachments ({{bytes}} total).
        /// </summary>
        internal static string SideBarAttachmentsCounter_plural {
            get {
                return ResourceManager.GetString("SideBarAttachmentsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tab to upload multimedia files that may be referenced in the questionnaire..
        /// </summary>
        internal static string SideBarAttachmentsEmptyLine1 {
            get {
                return ResourceManager.GetString("SideBarAttachmentsEmptyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid slow synchronization we recommend combined size of all attached files not to exceed 2MB. For supported file types, formats, and dimensions.
        /// </summary>
        internal static string SideBarAttachmentsEmptyLine2 {
            get {
                return ResourceManager.GetString("SideBarAttachmentsEmptyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To refer to an attachment in the questionnaire add a static text element and specify the attachment {{- name}} in its attachment property.
        /// </summary>
        internal static string SideBarAttachmentsEmptyLine3 {
            get {
                return ResourceManager.GetString("SideBarAttachmentsEmptyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. loading time: {{timeString}} at {{downloadSpeed}}Kb/s (EDGE).
        /// </summary>
        internal static string SideBarAttachmentsEstimate {
            get {
                return ResourceManager.GetString("SideBarAttachmentsEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string SideBarAttachmentsTitle {
            get {
                return ResourceManager.GetString("SideBarAttachmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new.
        /// </summary>
        internal static string SideBarAttachmentsUpload {
            get {
                return ResourceManager.GetString("SideBarAttachmentsUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded: {{-lastUpdate, MMMM DD[,] YYYY [at] k:mm}}.
        /// </summary>
        internal static string SideBarAttachmentUploaded {
            get {
                return ResourceManager.GetString("SideBarAttachmentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tab to define lookup tables..
        /// </summary>
        internal static string SideBarLookupEmptyLine1 {
            get {
                return ResourceManager.GetString("SideBarLookupEmptyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lookup table provides reference information that may be queried by a key and used in enabling conditions and validation expressions..
        /// </summary>
        internal static string SideBarLookupEmptyLine2 {
            get {
                return ResourceManager.GetString("SideBarLookupEmptyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lookup table consists of a name and the lookup file, which may contain multiple tab-delimited columns of numeric values..
        /// </summary>
        internal static string SideBarLookupEmptyLine3 {
            get {
                return ResourceManager.GetString("SideBarLookupEmptyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW Lookup table.
        /// </summary>
        internal static string SideBarLookupTableAdd {
            get {
                return ResourceManager.GetString("SideBarLookupTableAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop File here.
        /// </summary>
        internal static string SideBarLookupTableDropFile {
            get {
                return ResourceManager.GetString("SideBarLookupTableDropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file name.
        /// </summary>
        internal static string SideBarLookupTableFileName {
            get {
                return ResourceManager.GetString("SideBarLookupTableFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table name.
        /// </summary>
        internal static string SideBarLookupTableName {
            get {
                return ResourceManager.GetString("SideBarLookupTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Lookup Table:.
        /// </summary>
        internal static string SideBarLookupTablesCounter {
            get {
                return ResourceManager.GetString("SideBarLookupTablesCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Lookup Tables:.
        /// </summary>
        internal static string SideBarLookupTablesCounter_plural {
            get {
                return ResourceManager.GetString("SideBarLookupTablesCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string SideBarLookupTableSelectFile {
            get {
                return ResourceManager.GetString("SideBarLookupTableSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file.
        /// </summary>
        internal static string SideBarLookupTableUpdateFile {
            get {
                return ResourceManager.GetString("SideBarLookupTableUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup tables.
        /// </summary>
        internal static string SideBarLookupTitle {
            get {
                return ResourceManager.GetString("SideBarLookupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        internal static string SideBarMacroContent {
            get {
                return ResourceManager.GetString("SideBarMacroContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Macro:.
        /// </summary>
        internal static string SideBarMacroCounter {
            get {
                return ResourceManager.GetString("SideBarMacroCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Macros:.
        /// </summary>
        internal static string SideBarMacroCounter_plural {
            get {
                return ResourceManager.GetString("SideBarMacroCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string SideBarMacroDescription {
            get {
                return ResourceManager.GetString("SideBarMacroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tab to define macro substitutions..
        /// </summary>
        internal static string SideBarMacroEmptyLine1 {
            get {
                return ResourceManager.GetString("SideBarMacroEmptyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A macro is a named expression that can be used in enabling conditions and validation expressions. A macro consists of name and content..
        /// </summary>
        internal static string SideBarMacroEmptyLine2 {
            get {
                return ResourceManager.GetString("SideBarMacroEmptyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use a macro in an expression, refer to it by its {{-substitution}}.
        /// </summary>
        internal static string SideBarMacroEmptyLine3 {
            get {
                return ResourceManager.GetString("SideBarMacroEmptyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide description.
        /// </summary>
        internal static string SideBarMacroHideDescription {
            get {
                return ResourceManager.GetString("SideBarMacroHideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macro name.
        /// </summary>
        internal static string SideBarMacroName {
            get {
                return ResourceManager.GetString("SideBarMacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add description.
        /// </summary>
        internal static string SideBarMacroShowDescription {
            get {
                return ResourceManager.GetString("SideBarMacroShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string SideBarMacroTitle {
            get {
                return ResourceManager.GetString("SideBarMacroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Section:.
        /// </summary>
        internal static string SideBarSectionsCounter {
            get {
                return ResourceManager.GetString("SideBarSectionsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Sections:.
        /// </summary>
        internal static string SideBarSectionsCounter_plural {
            get {
                return ResourceManager.GetString("SideBarSectionsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string SideBarSectionsTitle {
            get {
                return ResourceManager.GetString("SideBarSectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download xlsx.
        /// </summary>
        internal static string SideBarTranslationDownloadXlsx {
            get {
                return ResourceManager.GetString("SideBarTranslationDownloadXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Template for .
        /// </summary>
        internal static string SideBarTranslationGetTemplate {
            get {
                return ResourceManager.GetString("SideBarTranslationGetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel (xlsx).
        /// </summary>
        internal static string SideBarTranslationGetTemplateLinkTextXlsx {
            get {
                return ResourceManager.GetString("SideBarTranslationGetTemplateLinkTextXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation name.
        /// </summary>
        internal static string SideBarTranslationName {
            get {
                return ResourceManager.GetString("SideBarTranslationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Translation.
        /// </summary>
        internal static string SideBarTranslationsCounter {
            get {
                return ResourceManager.GetString("SideBarTranslationsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} Translations.
        /// </summary>
        internal static string SideBarTranslationsCounter_plural {
            get {
                return ResourceManager.GetString("SideBarTranslationsCounter_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tab to manage questionnaire translations..
        /// </summary>
        internal static string SideBarTranslationsEmptyLine1 {
            get {
                return ResourceManager.GetString("SideBarTranslationsEmptyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may download and update translations to different languages..
        /// </summary>
        internal static string SideBarTranslationsEmptyLine2 {
            get {
                return ResourceManager.GetString("SideBarTranslationsEmptyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation will be applied on original texts and override values. You may leave some texts empty to use default original translations..
        /// </summary>
        internal static string SideBarTranslationsEmptyLine3 {
            get {
                return ResourceManager.GetString("SideBarTranslationsEmptyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string SideBarTranslationsTitle {
            get {
                return ResourceManager.GetString("SideBarTranslationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new translation.
        /// </summary>
        internal static string SideBarTranslationsUploadNew {
            get {
                return ResourceManager.GetString("SideBarTranslationsUploadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static text.
        /// </summary>
        internal static string StaticText {
            get {
                return ResourceManager.GetString("StaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment name.
        /// </summary>
        internal static string StaticTextAttachmentName {
            get {
                return ResourceManager.GetString("StaticTextAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dropdown.
        /// </summary>
        internal static string ToggleDropdown {
            get {
                return ResourceManager.GetString("ToggleDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Search.
        /// </summary>
        internal static string ToggleSearch {
            get {
                return ResourceManager.GetString("ToggleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        internal static string TreeAddQuestion {
            get {
                return ResourceManager.GetString("TreeAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question after.
        /// </summary>
        internal static string TreeAddQuestionAfter {
            get {
                return ResourceManager.GetString("TreeAddQuestionAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add roster.
        /// </summary>
        internal static string TreeAddRoster {
            get {
                return ResourceManager.GetString("TreeAddRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add roster after.
        /// </summary>
        internal static string TreeAddRosterAfter {
            get {
                return ResourceManager.GetString("TreeAddRosterAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub-section.
        /// </summary>
        internal static string TreeAddSection {
            get {
                return ResourceManager.GetString("TreeAddSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub-section after.
        /// </summary>
        internal static string TreeAddSectionAfter {
            get {
                return ResourceManager.GetString("TreeAddSectionAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add static text.
        /// </summary>
        internal static string TreeAddStaticText {
            get {
                return ResourceManager.GetString("TreeAddStaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add static text after.
        /// </summary>
        internal static string TreeAddStaticTextAfter {
            get {
                return ResourceManager.GetString("TreeAddStaticTextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variable.
        /// </summary>
        internal static string TreeAddVariable {
            get {
                return ResourceManager.GetString("TreeAddVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variable after.
        /// </summary>
        internal static string TreeAddVariableAfter {
            get {
                return ResourceManager.GetString("TreeAddVariableAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roster:.
        /// </summary>
        internal static string TreeRoster {
            get {
                return ResourceManager.GetString("TreeRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation condition.
        /// </summary>
        internal static string ValidationCondition {
            get {
                return ResourceManager.GetString("ValidationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string VariableExpression {
            get {
                return ResourceManager.GetString("VariableExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable label.
        /// </summary>
        internal static string VariableLabel {
            get {
                return ResourceManager.GetString("VariableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable type.
        /// </summary>
        internal static string VariableType {
            get {
                return ResourceManager.GetString("VariableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} warning.
        /// </summary>
        internal static string WarningsCounter {
            get {
                return ResourceManager.GetString("WarningsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{count}} warnings.
        /// </summary>
        internal static string WarningsCounter_plural {
            get {
                return ResourceManager.GetString("WarningsCounter_plural", resourceCulture);
            }
        }
    }
}
