ARG NODEJS_VERSION
ARG DOTNET_VERSION

FROM node:${NODEJS_VERSION} AS js_builder

COPY src/ /src
WORKDIR /src/UI/WB.UI.Frontend
RUN yarn && yarn build --package

FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as builder

COPY src /src
COPY --from=js_builder /src/UI/WB.UI.Frontend/dist/package/hq /src/UI/WB.UI.Headquarters.Core/
RUN dotnet publish /src/UI/WB.UI.Headquarters.Core/WB.UI.Headquarters.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:${DOTNET_VERSION}
COPY --from=builder app /app

WORKDIR /app

EXPOSE 5000

ENV HQ_Headquarters__BaseUrl=http://localhost:5000

ENTRYPOINT ["dotnet", "WB.UI.Headquarters.dll", "--urls=http://+:5000"]
