//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.UI.Headquarters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InterviewerAuditRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterviewerAuditRecord() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.UI.Headquarters.Resources.InterviewerAuditRecord", typeof(InterviewerAuditRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} approved.
        /// </summary>
        public static string ApproveInterview {
            get {
                return ResourceManager.GetString("ApproveInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign responsible {0} to assignment #{1}.
        /// </summary>
        public static string AssignResponsibleToAssignment {
            get {
                return ResourceManager.GetString("AssignResponsibleToAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign responsible {0} to interview {1}.
        /// </summary>
        public static string AssignResponsibleToInterview {
            get {
                return ResourceManager.GetString("AssignResponsibleToInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} closed.
        /// </summary>
        public static string CloseInterview {
            get {
                return ResourceManager.GetString("CloseInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} completed.
        /// </summary>
        public static string CompleteInterview {
            get {
                return ResourceManager.GetString("CompleteInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} created from assignment {1}.
        /// </summary>
        public static string CreateInterviewFromAssignment {
            get {
                return ResourceManager.GetString("CreateInterviewFromAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} deleted.
        /// </summary>
        public static string DeleteInterview {
            get {
                return ResourceManager.GetString("DeleteInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed action log.
        /// </summary>
        public static string DetailedActionLog {
            get {
                return ResourceManager.GetString("DetailedActionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete log in Tab format.
        /// </summary>
        public static string DownloadTabLog {
            get {
                return ResourceManager.GetString("DownloadTabLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} logged in application.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} logout from application.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application opened.
        /// </summary>
        public static string OpenApplication {
            get {
                return ResourceManager.GetString("OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} opened.
        /// </summary>
        public static string OpenInterview {
            get {
                return ResourceManager.GetString("OpenInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action log.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview {0} rejected.
        /// </summary>
        public static string RejectInterview {
            get {
                return ResourceManager.GetString("RejectInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User relinked to new tablet.
        /// </summary>
        public static string Relink {
            get {
                return ResourceManager.GetString("Relink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records yet.
        /// </summary>
        public static string RocordsMissing {
            get {
                return ResourceManager.GetString("RocordsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show previous 7 active days.
        /// </summary>
        public static string ShowPrevious7Days {
            get {
                return ResourceManager.GetString("ShowPrevious7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync canceled.
        /// </summary>
        public static string SynchronizationCanceled {
            get {
                return ResourceManager.GetString("SynchronizationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync completed:.
        /// </summary>
        public static string SynchronizationCompleted {
            get {
                return ResourceManager.GetString("SynchronizationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new assignment(s) downloaded.
        /// </summary>
        public static string SynchronizationCompleted_AssignmentsDownloaded {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_AssignmentsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} assignment(s) removed.
        /// </summary>
        public static string SynchronizationCompleted_AssignmentsRemoved {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_AssignmentsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new interview(s) downloaded.
        /// </summary>
        public static string SynchronizationCompleted_InterviewsDownloaded {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_InterviewsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} interview(s) rejected.
        /// </summary>
        public static string SynchronizationCompleted_InterviewsRejected {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_InterviewsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} interview(s) removed.
        /// </summary>
        public static string SynchronizationCompleted_InterviewsRemoved {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_InterviewsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} interview(s) uploaded.
        /// </summary>
        public static string SynchronizationCompleted_InterviewsUploaded {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_InterviewsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing to sync.
        /// </summary>
        public static string SynchronizationCompleted_NothingToSync {
            get {
                return ResourceManager.GetString("SynchronizationCompleted_NothingToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed.
        /// </summary>
        public static string SynchronizationFailed {
            get {
                return ResourceManager.GetString("SynchronizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync started ({0}).
        /// </summary>
        public static string SynchronizationStarted {
            get {
                return ResourceManager.GetString("SynchronizationStarted", resourceCulture);
            }
        }
    }
}
