//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB.UI.Headquarters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebInterviewSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebInterviewSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WB.UI.Headquarters.Resources.WebInterviewSettings", typeof(WebInterviewSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize displayed text for respondents.
        /// </summary>
        internal static string CustomizeDisplayedText {
            get {
                return ResourceManager.GetString("CustomizeDisplayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize emails text.
        /// </summary>
        internal static string CustomizeEmailsText {
            get {
                return ResourceManager.GetString("CustomizeEmailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string EmailMessage {
            get {
                return ResourceManager.GetString("EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Finish Page.
        /// </summary>
        internal static string ExampleFinishPage {
            get {
                return ResourceManager.GetString("ExampleFinishPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Invitation Email message.
        /// </summary>
        internal static string ExampleInvitationEmailMessage {
            get {
                return ResourceManager.GetString("ExampleInvitationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Reject Email message.
        /// </summary>
        internal static string ExampleRejectEmailMessage {
            get {
                return ResourceManager.GetString("ExampleRejectEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Reminder Email message.
        /// </summary>
        internal static string ExampleReminderEmailMessage {
            get {
                return ResourceManager.GetString("ExampleReminderEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Resume Page.
        /// </summary>
        internal static string ExampleResumePage {
            get {
                return ResourceManager.GetString("ExampleResumePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of the Welcome Page.
        /// </summary>
        internal static string ExampleWelcomePage {
            get {
                return ResourceManager.GetString("ExampleWelcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Page.
        /// </summary>
        internal static string FinishPage {
            get {
                return ResourceManager.GetString("FinishPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation.
        /// </summary>
        internal static string Invitation {
            get {
                return ResourceManager.GetString("Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation.
        /// </summary>
        internal static string InvitationEmailMessage {
            get {
                return ResourceManager.GetString("InvitationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectEmailMessage {
            get {
                return ResourceManager.GetString("RejectEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response.
        /// </summary>
        internal static string ReminderNoResponseEmailMessage {
            get {
                return ResourceManager.GetString("ReminderNoResponseEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Response.
        /// </summary>
        internal static string ReminderPartialResponseEmailMessage {
            get {
                return ResourceManager.GetString("ReminderPartialResponseEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder setting.
        /// </summary>
        internal static string ReminderSetting {
            get {
                return ResourceManager.GetString("ReminderSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Page.
        /// </summary>
        internal static string ResumePage {
            get {
                return ResourceManager.GetString("ResumePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web interview setup for .
        /// </summary>
        internal static string WebInterviewSetupFor_Title {
            get {
                return ResourceManager.GetString("WebInterviewSetupFor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Page.
        /// </summary>
        internal static string WelcomePage {
            get {
                return ResourceManager.GetString("WelcomePage", resourceCulture);
            }
        }
    }
}
