name: Smoke Test

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REPO: surveysolutions/surveysolutions
  DOCKER_NETWORK: automation_network
  TEAMCITY_PASSWORD: ${{secrets.TEAMCITY_PASSWORD}}
  TEAMCITY_USER:  ${{secrets.TEAMCITY_USER}}
  TEAMCITY_CACHE: /var/automation/cache
  TEAMCITY_PROJECT_NAME: automation
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TC_ARTIFACTS: $GITHUB_WORKSPACE/.run_artifacts
  
  TEST_CATEGORIES: "Web&TestCategory!=Preload&(TestCategory=Smoke|TestCategory=High)"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  wait-for-build:
    runs-on: kharkov

    steps:
    # - name: Wait for build to succeed
    #   id: waitforstatuschecks
    #   uses: "WyriHaximus/github-action-wait-for-status@4c9e58820905eb246e88a413c39a9104cccf7e80"
    #   with:
    #     checkInterval: 30
    #     ignoreActions: wait-for-build 
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Do something with a failing build
      run: echo ok
      #if: steps.wait-for-build.outputs.conclusion == 'failure'
      #run: throw

  prepare-images:

    runs-on: kharkov

    needs: [ wait-for-build ] 

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: surveysolutions/automatedtesting
        token: ${{secrets.PAT_AUTOMATION}}

    # - name: Cache artifacts
    #   uses: actions/cache@v2
    #   with:
    #       path: ${{ env.TEAMCITY_CACHE }}
    #       key: downloaded-artifacts-${{ runner.os }}

    - name: Build and push images
      run: pwsh ./compose.ps1 -branch ${{ github.head_ref }}  -skipApk -donotrun

  run-hq-tests:
    runs-on: kharkov
    needs: [ prepare-images ] 

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        project: ['UI.Headquarters', 'UI.Web.Interview', 'UI.Web.Interviewer']

    env:
      COMPOSE_PROJECT_NAME: github_actions_${{ matrix.project }}_${{ github.run_id }}

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: surveysolutions/automatedtesting
        token: ${{ secrets.PAT_AUTOMATION }}

    - name: Build ${{ matrix.project }}
      run: dotnet build Regression/${{ matrix.project }} -v q

    - name: Run env
      run: pwsh ./compose.ps1 -branch ${{ github.head_ref }}

    - name: Tests ${{ matrix.project }}
      run: dotnet test Regression/${{ matrix.project }} --no-build -v d --filter TestCategory="${{ env.TEST_CATEGORIES }}" -- NUnit.NumberOfTestWorkers=6
      env:
        SELENIUM_GRID_URI: http://localhost:4444/wd/hub
        AUTOMATION_QUIET: true

    - name: Cleanup
      if: ${{ always() }}
      run: pwsh ./compose.ps1 -down

    - name: Collect container logs
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      continue-on-error: true
      with:
        name: container-logs
        path: docker/logs/${{ env.COMPOSE_PROJECT_NAME }}

    - name: Collect runner logs
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      continue-on-error: true
      with:
        name: ${{ matrix.project }}-logs
        path: ${{ env.TC_ARTIFACTS }}

