name: Automated tests

on:
  pull_request:
    branches: [ master ]

jobs:
  prepare-images:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      DOCKER_REPO: surveysolutions/surveysolutions
      TEAMCITY_PASSWORD: ${{secrets.TEAMCITY_PASSWORD}}
      TEAMCITY_USER: ${{secrets.TEAMCITY_USER}}
      TEAMCITY_CACHE: ./.cache
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: surveysolutions/automatedtesting
        token: ${{secrets.PAT_AUTOMATION}}

    - name: Cache artifacts
      uses: actions/cache@v2
      with:
          path: ./.cache
          key: downloaded-artifacts-${{ runner.os }}

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and push images
      run: pwsh ./compose.ps1 -branch ${{ github.head_ref }} -skipApk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Start selenoid
    #   uses: Xotabu4/selenoid-github-action@v1

    - name: Tests UI.Web.Interview
      run: dotnet test Regression/UI.Headquarters --filter TestCategory="Web&TestCategory!=Preload&(TestCategory=Smoke|TestCategory=High)" -- NUnit.NumberOfTestWorkers=6
      env: 
        TEAMCITY_PROJECT_NAME: "automation" 
        # SELENIUM_GRID_URI: "http://localhost:4444/wd/hub" 
      

