name: Automated tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      DOCKER_REPO: surveysolutions/surveysolutions
      TEAMCITY_PASSWORD: ${{secrets.TEAMCITY_PASSWORD}}
      TEAMCITY_USER: ${{secrets.TEAMCITY_USER}}
      TEAMCITY_CACHE: ./.cache

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: surveysolutions/automatedtesting
        token: ${{secrets.PAT_AUTOMATION}}

    - name: Cache artifacts
      uses: actions/cache@v2
      with:
          path: ./.cache
          key: ${{ runner.os }}

    - name: Build and push images
      run: pwsh ./build-and-push-images.ps1 -branch ${{ github.head_ref }} -notParallel -skipApk
      
    - name: Docker up
      run: docker-compose up -f ./docker/docker-compose.yml up -d

    - name: Prepare HQ-Designer for test
      run: pwsh ./docker/finish.ps1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Tests UI.Web.Interview
      run: dotnet test Regression/UI.Web.Interview/UI.Web.Interview.csproj --filter TestCategory="Web&TestCategory!=Preload&(TestCategory=Smoke|TestCategory=High)" -- NUnit.NumberOfTestWorkers=6
      

