name: Packages cleanup

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Package name to delete"
        required: true
      numberOfVersions:
        description: "Number of versions to delete"
        required: true
        default: '3'
  
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: ${{ github.event.inputs.packageName }}
          num-old-versions-to-delete: ${{ github.event.inputs.numberOfVersions }}
