name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: Qwerty1234
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        ports:
          - 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - run: echo $POSTGRES_PORT && ping -c 1 -v postgres
      - run: dotnet build 'src/WB without Xamarin.sln' -c Debug
      - run: dotnet test 'src/WB without Xamarin.sln' -c Debug
      - run: dotnet test src/Services/WB.Services.sln -c Debug
